Azure/autorest.python

src/autorest.python.csproj, src/azure/TransformerPya.cs
replayed https://github.com/Azure/autorest/pull/2531
=> bump tooling version and replaying https://github.com/Azure/autorest/pull/2531

src/vanilla/Model/CodeModelPy.cs, src/vanilla/Templates/ServiceClientTemplate.cshtml
- Fix https://github.com/Azure/autorest/issues/2100
=> Add client-side-validation to Autorest.Python

ChangeLog.md, src/vanilla/Model/CodeModelPy.cs, test/azure/Expected/AcceptanceTests/AzureSpecials/fixtures/acceptancetestsazurespecials/auto_rest_azure_special_parameters_test_client.py, test/azure/Expected/AcceptanceTests/CustomBaseUri/fixtures/acceptancetestscustombaseuri/auto_rest_parameterized_host_test_client.py, test/azure/Expected/AcceptanceTests/StorageManagementClient/fixtures/acceptancetestsstoragemanagementclient/storage_management_client.py, test/azure/Expected/AcceptanceTests/SubscriptionIdApiVersion/fixtures/acceptancetestssubscriptionidapiversion/microsoft_azure_test_url.py, test/vanilla/Expected/AcceptanceTests/CustomBaseUri/auto_rest_parameterized_host_test_client/auto_rest_parameterized_host_test_client.py, test/vanilla/Expected/AcceptanceTests/CustomBaseUriMoreOptions/auto_rest_parameterized_custom_host_test_client/auto_rest_parameterized_custom_host_test_client.py, test/vanilla/Expected/AcceptanceTests/RequiredOptional/auto_rest_required_optional_test_service/auto_rest_required_optional_test_service.py, test/vanilla/Expected/AcceptanceTests/Url/auto_rest_url_test_service/auto_rest_url_test_service.py, test/vanilla/Expected/AcceptanceTests/Validation/auto_rest_validation_test/auto_rest_validation_test.py
Fix https://github.com/Azure/autorest/issues/2475
=> Stop checking type of str client param

ChangeLog.md, src/vanilla/Model/MethodPy.cs
Fix https://github.com/Azure/autorest/issues/2318
=> Fix https://github.com/Azure/autorest/issues/2318

ChangeLog.md, src/vanilla/Model/MethodPy.cs
Fix https://github.com/Azure/autorest/issues/2461
=> Fix invalid headers test

ChangeLog.md, src/vanilla/Model/CompositeTypePy.cs, src/vanilla/Templates/ModelTemplate.cshtml, test/vanilla/Expected/AcceptanceTests/BodyComplex/auto_rest_complex_test_service/models/cookiecuttershark.py, test/vanilla/Expected/AcceptanceTests/BodyComplex/auto_rest_complex_test_service/models/fish.py, test/vanilla/Expected/AcceptanceTests/BodyComplex/auto_rest_complex_test_service/models/goblinshark.py, test/vanilla/Expected/AcceptanceTests/BodyComplex/auto_rest_complex_test_service/models/salmon.py, test/vanilla/Expected/AcceptanceTests/BodyComplex/auto_rest_complex_test_service/models/sawshark.py, test/vanilla/Expected/AcceptanceTests/BodyComplex/auto_rest_complex_test_service/models/shark.py
https://github.com/Azure/autorest/issues/2462
=> Improve discriminator documentation

ChangeLog.md, src/vanilla/Model/ParameterPy.cs, src/vanilla/TransformerPy.cs
Fixes https://github.com/Azure/autorest/issues/2837
=> Fix baseUrl as a client parameter

ChangeLog.md, package.json, src/vanilla/Templates/EnumTemplate.cshtml, test/vanilla/AcceptanceTests/complex_tests.py, test/vanilla/Expected/AcceptanceTests/ExtensibleEnums/extensibleenumsswagger/models/pet_store_inc_enums.py
Fix https://github.com/Azure/autorest/issues/2704
FYI @matthchr
=> Add doc to enum

ChangeLog.md, src/vanilla/Model/CompositeTypePy.cs, src/vanilla/TransformerPy.cs
https://github.com/Azure/autorest/issues/2899
=> Fix bug 2889 - flattening and discriminator

test/vanilla/AcceptanceTests/asynctests/test_file.py, test/vanilla/AcceptanceTests/test_file.py
Adapt testsuite to https://github.com/Azure/azure-sdk-for-python/pull/6490
=> Adapt tests to new stream object

autorest/code_generator.py, autorest/jsonrpc/__init__.py, autorest/models/code_model.py, autorest/templates/config.py.jinja2
=> added authentication policy to config

autorest/codegen/models/primitive_schemas.py, test/vanilla/Expected/AcceptanceTests/BodyArray/bodyarray/aio/operations_async/_array_operations_async.py, test/vanilla/Expected/AcceptanceTests/BodyArray/bodyarray/operations/_array_operations.py, test/vanilla/Expected/AcceptanceTests/BodyDictionary/bodydictionary/aio/operations_async/_dictionary_operations_async.py, test/vanilla/Expected/AcceptanceTests/BodyDictionary/bodydictionary/operations/_dictionary_operations.py, test/vanilla/Expected/AcceptanceTests/BodyString/bodystring/aio/operations_async/_string_operations_async.py, test/vanilla/Expected/AcceptanceTests/BodyString/bodystring/operations/_string_operations.py, test/vanilla/Expected/AcceptanceTests/Url/url/aio/operations_async/_paths_operations_async.py, test/vanilla/Expected/AcceptanceTests/Url/url/operations/_paths_operations.py
=> having ByteArraySchema return both bytes and bytearrays for python type

autorest/namer/name_converter.py, test/vanilla/Expected/AcceptanceTests/BodyArray/bodyarray/aio/operations_async/_array_operations_async.py, test/vanilla/Expected/AcceptanceTests/BodyArray/bodyarray/models/__init__.py, test/vanilla/Expected/AcceptanceTests/BodyArray/bodyarray/models/_auto_rest_swagger_bat_array_service_enums.py, test/vanilla/Expected/AcceptanceTests/BodyArray/bodyarray/operations/_array_operations.py
=> Fix enum name (for example, ListBlobsIncludeItem from storage blob)

autorest/codegen/models/parameter.py, autorest/codegen/templates/keywords.jinja2, autorest/codegen/templates/operation.py.jinja2, autorest/codegen/templates/service_client.py.jinja2
Remove workaround of https://github.com/Azure/autorest.modelerfour/issues/123 and fix https://github.com/Azure/autorest.python/issues/331
=> Various fixes

autorest/codegen/models/code_model.py, autorest/codegen/models/schema_response.py, test/vanilla/Expected/AcceptanceTests/BodyFile/bodyfile/aio/operations_async/_files_operations_async.py, test/vanilla/Expected/AcceptanceTests/BodyFile/bodyfile/operations/_files_operations.py
fixes #226 
There's no type hinting yet bc that PR hasn't been merged yet
=> IO docstring

autorest/codegen/serializers/model_python3_serializer.py, test/azure/Expected/AcceptanceTests/Lro/lro/models/_models_py3.py, test/azure/Expected/AcceptanceTests/ModelFlattening/modelflattening/models/_models_py3.py, test/vanilla/Expected/AcceptanceTests/BodyComplex/bodycomplex/models/_models_py3.py, test/vanilla/Expected/AcceptanceTests/ModelFlattening/modelflattening/models/_models_py3.py, test/vanilla/Expected/AcceptanceTests/XmsErrorResponse/xmserrorresponse/models/_models_py3.py
Fix https://github.com/Azure/autorest.python/issues/339
=> Fix missing readonly

autorest/codegen/templates/enum.py.jinja2, test/azure/Expected/AcceptanceTests/Lro/lro/models/_auto_rest_long_running_operation_test_service_enums.py, test/azure/Expected/AcceptanceTests/ModelFlattening/modelflattening/models/_auto_rest_resource_flattening_test_service_enums.py, test/azure/Expected/AcceptanceTests/Paging/paging/models/_auto_rest_paging_test_service_enums.py, test/azure/Expected/AcceptanceTests/StorageManagementClient/storage/models/_storage_management_client_enums.py, test/vanilla/Expected/AcceptanceTests/BodyArray/bodyarray/models/_auto_rest_swagger_bat_array_service_enums.py, test/vanilla/Expected/AcceptanceTests/BodyComplex/bodycomplex/models/_auto_rest_complex_test_service_enums.py, test/vanilla/Expected/AcceptanceTests/BodyString/bodystring/models/_auto_rest_swagger_bat_service_enums.py, test/vanilla/Expected/AcceptanceTests/ExtensibleEnums/extensibleenumsswagger/models/_pet_store_inc_enums.py, test/vanilla/Expected/AcceptanceTests/Header/header/models/_auto_rest_swagger_bat_header_service_enums.py, test/vanilla/Expected/AcceptanceTests/ModelFlattening/modelflattening/models/_auto_rest_resource_flattening_test_service_enums.py, test/vanilla/Expected/AcceptanceTests/Url/url/models/_auto_rest_url_test_service_enums.py, test/vanilla/Expected/AcceptanceTests/Xml/xmlservice/models/_auto_rest_swagger_batxml_service_enums.py
=> Fix whitespace enums

autorest/namer/__init__.py, autorest/namer/name_converter.py
=> Remove override_client_name hack

autorest/codegen/models/base_schema.py, autorest/codegen/models/code_model.py, autorest/codegen/models/constant_schema.py, autorest/codegen/models/dictionary_schema.py, autorest/codegen/models/enum_schema.py, autorest/codegen/models/list_schema.py, autorest/codegen/models/object_schema.py, autorest/codegen/models/operation.py, autorest/codegen/models/primitive_schemas.py, autorest/codegen/templates/lro_operation.py.jinja2, autorest/codegen/templates/model.py.jinja2, autorest/codegen/templates/operation.py.jinja2, autorest/codegen/templates/operation_tools.jinja2, autorest/codegen/templates/paging_operation.py.jinja2
=> made serialization_type a property of schemas

autorest/codegen/models/dictionary_schema.py, autorest/codegen/models/list_schema.py, autorest/codegen/models/object_schema.py, autorest/codegen/serializers/__init__.py, autorest/codegen/serializers/model_base_serializer.py, autorest/codegen/serializers/model_generic_serializer.py, autorest/codegen/serializers/model_python3_serializer.py, tasks.py
=> switched format strings to f strings where possible

autorest/__init__.py, autorest/codegen/__init__.py, autorest/m2r/__init__.py, autorest/namer/__init__.py, autorest/namer/name_converter.py
=> Rename all yaml_code_models to yaml_data

autorest/codegen/models/base_schema.py, autorest/codegen/models/constant_schema.py, autorest/codegen/models/list_schema.py, autorest/codegen/models/operation.py, autorest/codegen/models/primitive_schemas.py, autorest/codegen/models/property.py, autorest/codegen/serializers/model_generic_serializer.py, autorest/codegen/serializers/model_python3_serializer.py, autorest/codegen/templates/config.py.jinja2, autorest/codegen/templates/model.py.jinja2, autorest/codegen/templates/operation.py.jinja2, autorest/codegen/templates/paging_operation.py.jinja2
=> Getters to properties

autorest/codegen/serializers/general_serializer.py
=> Getting rid of unnecessary properties in GeneralSerializer

autorest/codegen/serializers/__init__.py
=> Correct logic used to generate version file

autorest/namer/name_converter.py
=> Generate Operations operation group instead of OperationsOperations

autorest/codegen/models/primitive_schemas.py, test/vanilla/Expected/AcceptanceTests/Validation/validation/aio/operations_async/_auto_rest_validation_test_operations_async.py, test/vanilla/Expected/AcceptanceTests/Validation/validation/models/_models.py, test/vanilla/Expected/AcceptanceTests/Validation/validation/models/_models_py3.py, test/vanilla/Expected/AcceptanceTests/Validation/validation/operations/_auto_rest_validation_test_operations.py
=> Use raw strings for pattern matching

autorest/codegen/serializers/operation_group_serializer.py
=> Generate _operations.py instead of _operations_operations.py

autorest/namer/name_converter.py, test/unittests/test_name_converter.py, test/vanilla/AcceptanceTests/test_xml.py, test/vanilla/Expected/AcceptanceTests/Xml/xmlservice/models/_models.py, test/vanilla/Expected/AcceptanceTests/Xml/xmlservice/models/_models_py3.py
=> dealing with reserved words

autorest/codegen/models/dictionary_schema.py, autorest/codegen/models/object_schema.py
=> Removing special case for DictionarySchema that is for additional properties

autorest/codegen/models/__init__.py
=> Don't generate empty objects

autorest/codegen/templates/enum.py.jinja2, autorest/namer/name_converter.py, test/azure/Expected/AcceptanceTests/Lro/lro/models/_auto_rest_long_running_operation_test_service_enums.py, test/azure/Expected/AcceptanceTests/Paging/paging/models/_auto_rest_paging_test_service_enums.py, test/azure/Expected/AcceptanceTests/StorageManagementClient/storage/models/_storage_management_client_enums.py, test/vanilla/Expected/AcceptanceTests/BodyComplex/bodycomplex/models/_auto_rest_complex_test_service_enums.py, test/vanilla/Expected/AcceptanceTests/ExtensibleEnums/extensibleenumsswagger/models/_pet_store_inc_enums.py
=> added enum description

autorest/codegen/serializers/metadata_serializer.py
=> sorting api version list in metadata

autorest/codegen/models/parameter_list.py, test/unittests/test_parameter_ordering.py
=> sorting parameters by default value and whether it's required

README.md, test/azure/AcceptanceTests/asynctests/test_parameter.py, test/azure/AcceptanceTests/test_parameter.py, test/azure/Expected/AcceptanceTests/AzureSpecials/azurespecialproperties/aio/operations_async/_api_version_local_operations_async.py, test/azure/Expected/AcceptanceTests/AzureSpecials/azurespecialproperties/operations/_api_version_local_operations.py
Should proove https://github.com/Azure/autorest.modelerfour/issues/93 is fixed
fixes #462
=> Update to last m4 to fix bug 93

autorest/codegen/templates/paging_operation.py.jinja2, test/azure/Expected/AcceptanceTests/CustomUrlPaging/custombaseurlpaging/aio/operations_async/_paging_operations_async.py, test/azure/Expected/AcceptanceTests/CustomUrlPaging/custombaseurlpaging/operations/_paging_operations.py, test/azure/Expected/AcceptanceTests/Paging/paging/aio/operations_async/_paging_operations_async.py, test/azure/Expected/AcceptanceTests/Paging/paging/operations/_paging_operations.py
=> making empty nextLink none

autorest/codegen/models/operation.py, autorest/codegen/models/operation_group.py, autorest/codegen/serializers/operation_group_serializer.py, autorest/codegen/templates/operations_container.py.jinja2
=> Unify criteria for importing and setting models in operation groups

package.json, test/vanilla/AcceptanceTests/asynctests/test_string_tests.py, test/vanilla/AcceptanceTests/test_string_tests.py, test/vanilla/Expected/AcceptanceTests/BodyString/bodystring/aio/operations_async/_string_operations_async.py, test/vanilla/Expected/AcceptanceTests/BodyString/bodystring/operations/_string_operations.py
after testserver change: https://github.com/Azure/autorest.testserver/pull/145
=> Update string tests

autorest/codegen/serializers/__init__.py, autorest/multiapi/__init__.py
=> switiching version.py -> _version.py if we want to keep version file

package.json, test/vanilla/AcceptanceTests/asynctests/test_non_string_enums.py, test/vanilla/AcceptanceTests/test_non_string_enums.py, test/vanilla/Expected/AcceptanceTests/NonStringEnums/nonstringenums/models/_non_string_enums_client_enums.py
based off this testserver issue: https://github.com/Azure/autorest.testserver/issues/161
=> changed posted float behavior for non string enums test

autorest/codegen/models/enum_schema.py, autorest/codegen/templates/enum_container.py.jinja2, test/azure/Expected/AcceptanceTests/Lro/lro/models/_auto_rest_long_running_operation_test_service_enums.py, test/azure/Expected/AcceptanceTests/StorageManagementClient/storage/models/_storage_management_client_enums.py, test/vanilla/Expected/AcceptanceTests/BodyArray/bodyarray/models/_auto_rest_swagger_bat_array_service_enums.py, test/vanilla/Expected/AcceptanceTests/NonStringEnums/nonstringenums/models/_non_string_enums_client_enums.py, test/vanilla/Expected/AcceptanceTests/Xml/xmlservice/models/_auto_rest_swagger_batxml_service_enums.py
=> order enums alphabetically

autorest/codegen/models/lro_operation.py
=> Fix lro multiple schema responses

ChangeLog.md, autorest/codegen/__init__.py
=> disable client side validation by default

autorest/multiapi/__init__.py, test/multiapi/AcceptanceTests/test_multiapi.py, test/multiapi/Expected/AcceptanceTests/Multiapi/multiapi/patch.py
=> Not overwriting patch file in multiapi

README.md, tasks.py
Implement https://github.com/Azure/autorest.modelerfour/issues/181
=> Prevent parameter flattening for multiple requests input

ChangeLog.md, autorest/codegen/templates/paging_operation.py.jinja2, package.json, test/azure/AcceptanceTests/asynctests/test_paging.py, test/azure/AcceptanceTests/test_paging.py, test/azure/Expected/AcceptanceTests/CustomUrlPaging/custombaseurlpaging/aio/operations_async/_paging_operations_async.py, test/azure/Expected/AcceptanceTests/CustomUrlPaging/custombaseurlpaging/operations/_paging_operations.py, test/azure/Expected/AcceptanceTests/Paging/paging/aio/operations_async/_paging_operations_async.py, test/azure/Expected/AcceptanceTests/Paging/paging/operations/_paging_operations.py, test/azure/Expected/AcceptanceTests/StorageManagementClient/storage/aio/operations_async/_storage_accounts_operations_async.py, test/azure/Expected/AcceptanceTests/StorageManagementClient/storage/operations/_storage_accounts_operations.py, test/multiapi/Expected/AcceptanceTests/Multiapi/multiapi/v3/aio/operations_async/_multiapi_service_client_operations_async.py, test/multiapi/Expected/AcceptanceTests/Multiapi/multiapi/v3/operations/_multiapi_service_client_operations.py, test/multiapi/Expected/AcceptanceTests/MultiapiNoAsync/multiapinoasync/v3/operations/_multiapi_service_client_operations.py, test/multiapi/Expected/AcceptanceTests/MultiapiWithSubmodule/multiapiwithsubmodule/submodule/v3/aio/operations_async/_multiapi_service_client_operations_async.py, test/multiapi/Expected/AcceptanceTests/MultiapiWithSubmodule/multiapiwithsubmodule/submodule/v3/operations/_multiapi_service_client_operations.py
Needs this testserver pr to be merged first: https://github.com/Azure/autorest.testserver/pull/172
for new storage import export, see: https://github.com/iscai-msft/azure-sdk-for-python/blob/bae8cb577dab07a9b98cfb7e0a8fa969adf68510/sdk/storage/azure-mgmt-storageimportexport/azure/mgmt/storageimportexport/operations/_jobs_operations.py#L48
for graphrbac see: (https://github.com/iscai-msft/azure-sdk-for-python/blob/898a7a16f5e4e47cae3ca368f579b92f988260a3/sdk/graphrbac/azure-graphrbac/azure/graphrbac/operations/_groups_operations.py#L296
=> Query params paging

ChangeLog.md, README.md
=> add include_apis to readme overrides

autorest/multiapi/__init__.py
=> make operation mixin output deterministic

run-python3.js
Slight improvement on error output in the script added in PR #631.
=> Improve error output on run-python3.js

package.json
Missed this in PR #632, thanks @iscai-msft for catching it!
=> Add run-python3.js to package.json's file manifest

test/vanilla/AcceptanceTests/asynctests/test_complex.py, test/vanilla/AcceptanceTests/asynctests/test_header.py, test/vanilla/AcceptanceTests/test_complex.py, test/vanilla/AcceptanceTests/test_header.py
updating to msrest changes: Azure/msrest-for-python@8be4f70
=> update tests for datetime rfc changes in msrest

autorest/codegen/__init__.py
this pr needs to be merged first to fix ci problems: https://github.com/Azure/autorest.python/pull/639
=> better warning message for credential scopes

ChangeLog.md, autorest/codegen/models/code_model.py, autorest/codegen/models/primitive_schemas.py
=> Fix storage blob generation by calling super init for IOSchema

README.md
Based on feedback from @mayankiitg in issue #625, I'm adding a link to the wiki about generating to the readme for discoverability
=> added generating wiki to readme for better disocverability

test/multiapi/AcceptanceTests/conftest.py, test/unittests/test_accept_content_type.py, test/unittests/test_name_converter.py, test/unittests/test_parameter_ordering.py, test/unittests/test_sort_schema.py
=> add missing license headers

tasks.py
=> clean up tasks file

autorest/codegen/serializers/model_base_serializer.py, autorest/codegen/serializers/model_generic_serializer.py, autorest/codegen/serializers/model_python3_serializer.py, tasks.py
=> deduplicate model serialization code

ChangeLog.md, README.md, autorest/codegen/models/parameter.py, autorest/codegen/templates/operation_tools.jinja2, autorest/namer/name_converter.py, package.json, test/azure/AcceptanceTests/asynctests/test_parameter.py, test/azure/AcceptanceTests/test_parameter.py, test/azure/Expected/AcceptanceTests/AzureParameterGrouping/azureparametergrouping/aio/operations/_parameter_grouping_operations.py, test/azure/Expected/AcceptanceTests/AzureParameterGrouping/azureparametergrouping/models/__init__.py, test/azure/Expected/AcceptanceTests/AzureParameterGrouping/azureparametergrouping/models/_models.py, test/azure/Expected/AcceptanceTests/AzureParameterGrouping/azureparametergrouping/models/_models_py3.py, test/azure/Expected/AcceptanceTests/AzureParameterGrouping/azureparametergrouping/operations/_parameter_grouping_operations.py
blocked by https://github.com/Azure/autorest.testserver/pull/295
=> fix case of grouped parameter + reserved property name

autorest/codegen/__init__.py
=> switch models mode flag to msrest or none

setup.py
=> make sure mistune is less than 2.x.x

eng/pipelines/ci.yml
=> storage moved to main branch

autorest/codegen/__init__.py
cc @msyyc, i'm making a separate branch where we do all of the updates related to m4 changes
=> update security checks

ChangeLog.md, autorest/m4reformatter/__init__.py, package.json, test/azure/low-level/Expected/AcceptanceTests/StorageManagementClientLowLevel/storagelowlevel/rest/storage_accounts/_request_builders.py, test/azure/low-level/Expected/AcceptanceTests/StorageManagementClientLowLevel/storagelowlevel/rest/storage_accounts/_request_builders_py3.py, test/azure/version-tolerant/Expected/AcceptanceTests/AzureSpecialsVersionTolerant/azurespecialpropertiesversiontolerant/aio/operations/_operations.py, test/azure/version-tolerant/Expected/AcceptanceTests/AzureSpecialsVersionTolerant/azurespecialpropertiesversiontolerant/operations/_operations.py, test/azure/version-tolerant/Expected/AcceptanceTests/StorageManagementClientVersionTolerant/storageversiontolerant/aio/operations/_operations.py, test/azure/version-tolerant/Expected/AcceptanceTests/StorageManagementClientVersionTolerant/storageversiontolerant/operations/_operations.py, test/azure/version-tolerant/Expected/AcceptanceTests/SubscriptionIdApiVersionVersionTolerant/subscriptionidapiversionversiontolerant/aio/operations/_operations.py, test/azure/version-tolerant/Expected/AcceptanceTests/SubscriptionIdApiVersionVersionTolerant/subscriptionidapiversionversiontolerant/operations/_operations.py, test/vanilla/low-level/Expected/AcceptanceTests/BodyComplexLowLevel/bodycomplexlowlevel/rest/basic/_request_builders.py, test/vanilla/low-level/Expected/AcceptanceTests/BodyComplexLowLevel/bodycomplexlowlevel/rest/basic/_request_builders_py3.py, test/vanilla/low-level/Expected/AcceptanceTests/ValidationLowLevel/validationlowlevel/rest/_request_builders.py, test/vanilla/low-level/Expected/AcceptanceTests/ValidationLowLevel/validationlowlevel/rest/_request_builders_py3.py, test/vanilla/version-tolerant/AcceptanceTests/asynctests/test_complex.py, test/vanilla/version-tolerant/AcceptanceTests/asynctests/test_inputs.py, test/vanilla/version-tolerant/AcceptanceTests/test_complex.py, test/vanilla/version-tolerant/AcceptanceTests/test_inputs.py, test/vanilla/version-tolerant/Expected/AcceptanceTests/BodyComplexVersionTolerant/bodycomplexversiontolerant/aio/operations/_operations.py, test/vanilla/version-tolerant/Expected/AcceptanceTests/BodyComplexVersionTolerant/bodycomplexversiontolerant/operations/_operations.py, test/vanilla/version-tolerant/Expected/AcceptanceTests/ValidationVersionTolerant/validationversiontolerant/_operations/_operations.py, test/vanilla/version-tolerant/Expected/AcceptanceTests/ValidationVersionTolerant/validationversiontolerant/aio/_operations/_operations.py
=> not allow api version input for dpg

ChangeLog.md
=> Fix changelog date

ChangeLog.md, autorest/codegen/models/model_type.py, autorest/codegen/serializers/builder_serializer.py, test/azure/version-tolerant/Expected/AcceptanceTests/StorageManagementClientVersionTolerant/storageversiontolerant/aio/operations/_operations.py, test/azure/version-tolerant/Expected/AcceptanceTests/StorageManagementClientVersionTolerant/storageversiontolerant/operations/_operations.py, test/vanilla/version-tolerant/Expected/AcceptanceTests/AdditionalPropertiesVersionTolerant/additionalpropertiesversiontolerant/aio/operations/_operations.py, test/vanilla/version-tolerant/Expected/AcceptanceTests/AdditionalPropertiesVersionTolerant/additionalpropertiesversiontolerant/operations/_operations.py, test/vanilla/version-tolerant/Expected/AcceptanceTests/BodyComplexVersionTolerant/bodycomplexversiontolerant/aio/operations/_operations.py, test/vanilla/version-tolerant/Expected/AcceptanceTests/BodyComplexVersionTolerant/bodycomplexversiontolerant/operations/_operations.py, test/vanilla/version-tolerant/Expected/AcceptanceTests/ExtensibleEnumsVersionTolerant/extensibleenumsswaggerversiontolerant/aio/operations/_operations.py, test/vanilla/version-tolerant/Expected/AcceptanceTests/ExtensibleEnumsVersionTolerant/extensibleenumsswaggerversiontolerant/operations/_operations.py, test/vanilla/version-tolerant/Expected/AcceptanceTests/ModelFlatteningVersionTolerant/modelflatteningversiontolerant/_operations/_operations.py, test/vanilla/version-tolerant/Expected/AcceptanceTests/ModelFlatteningVersionTolerant/modelflatteningversiontolerant/aio/_operations/_operations.py, test/vanilla/version-tolerant/Expected/AcceptanceTests/MultipleInheritanceVersionTolerant/multipleinheritanceversiontolerant/_operations/_operations.py, test/vanilla/version-tolerant/Expected/AcceptanceTests/MultipleInheritanceVersionTolerant/multipleinheritanceversiontolerant/aio/_operations/_operations.py, test/vanilla/version-tolerant/Expected/AcceptanceTests/ValidationVersionTolerant/validationversiontolerant/_operations/_operations.py, test/vanilla/version-tolerant/Expected/AcceptanceTests/ValidationVersionTolerant/validationversiontolerant/aio/_operations/_operations.py, test/vanilla/version-tolerant/Expected/AcceptanceTests/XmlVersionTolerant/xmlserviceversiontolerant/aio/operations/_operations.py, test/vanilla/version-tolerant/Expected/AcceptanceTests/XmlVersionTolerant/xmlserviceversiontolerant/operations/_operations.py
fix https://github.com/Azure/autorest.python/issues/1313
=> order required parameters first in JSON input docstrings

packages/autorest.python/autorest/_utils.py, packages/autorest.python/autorest/codegen/models/utils.py, packages/autorest.python/autorest/m4reformatter/__init__.py, packages/autorest.python/autorest/preprocess/__init__.py
Decompose adding overload for application/json operations logic. This way both cadl and autorest code models benefit from this logic
=> decompose adding overload

packages/autorest.python/ChangeLog.md, packages/autorest.python/autorest/multiapi/templates/multiapi_init.py.jinja2, packages/autorest.python/samples/specification/multiapi/generated/azure/multiapi/sample/__init__.py, packages/autorest.python/test/multiapi/Expected/AcceptanceTests/Multiapi/multiapi/__init__.py, packages/autorest.python/test/multiapi/Expected/AcceptanceTests/MultiapiCredentialDefaultPolicy/multiapicredentialdefaultpolicy/__init__.py, packages/autorest.python/test/multiapi/Expected/AcceptanceTests/MultiapiCustomBaseUrl/multiapicustombaseurl/__init__.py, packages/autorest.python/test/multiapi/Expected/AcceptanceTests/MultiapiDataPlane/multiapidataplane/__init__.py, packages/autorest.python/test/multiapi/Expected/AcceptanceTests/MultiapiNoAsync/multiapinoasync/__init__.py, packages/autorest.python/test/multiapi/Expected/AcceptanceTests/MultiapiSecurity/multiapisecurity/__init__.py, packages/autorest.python/test/multiapi/Expected/AcceptanceTests/MultiapiWithSubmodule/multiapiwithsubmodule/submodule/__init__.py
Fix https://github.com/Azure/autorest.python/issues/1392
=> add __version__ to init file for multiapi 

packages/autorest.python/ChangeLog.md, packages/autorest.python/autorest/preprocess/__init__.py
fix https://github.com/Azure/autorest.python/issues/1400
=> fix circular recursion for lropaging

packages/cadl-python/src/emitter.ts, packages/cadl-python/test/generated/dev-driven/resiliency/devdriven/_operations/_operations.py, packages/cadl-python/test/generated/dev-driven/resiliency/devdriven/aio/_operations/_operations.py
Fix https://github.com/Azure/autorest.python/issues/1417
https://github.com/Azure/cadl-azure/blob/main/packages/cadl-samples/data-plane/language/authoring/authoring.cadl
=> [cadl-python] Fix anonymous model and problematic response which has surplus parameter

eng/pipelines/ci.yml
https://github.com/Azure/autorest.python/issues/1455
=> add  `windows` for CI

packages/autorest.python/ChangeLog.md, packages/autorest.python/autorest/m4reformatter/__init__.py, packages/autorest.python/package.json
Be able to detect json content types with charset sections as json bodies
=> remove charset from json detection

packages/autorest.python/ChangeLog.md, packages/autorest.python/autorest/postprocess/__init__.py
1. fix for windows: replace "\r\n" with "\n" after reading file
2. fix for embeded namespaces
=> fix postprocess

packages/autorest.python/ChangeLog.md, packages/autorest.python/autorest/codegen/models/__init__.py, packages/autorest.python/autorest/m4reformatter/__init__.py
Fix https://github.com/Azure/autorest.python/issues/1483
=> support arm-id

packages/autorest.python/ChangeLog.md, packages/autorest.python/autorest/codegen/serializers/__init__.py
fix https://github.com/Azure/autorest.python/issues/1521
=> Fix generate sample

packages/cadl-python/CHANGELOG.md, packages/cadl-python/src/emitter.ts
CLient's names can be submodules of the service namespace
=> get namespace from client name

packages/autorest.python/ChangeLog.md, packages/autorest.python/package.json, packages/cadl-python/CHANGELOG.md, packages/cadl-python/package.json, pnpm-lock.yaml
=> make cadl-dpg a dep

packages/cadl-python/package.json
=> fix links to point to autorest.python repo

packages/autorest.python/ChangeLog.md, packages/autorest.python/autorest/codegen/templates/model_base.py.jinja2, packages/cadl-python/test/generated/api-key/authentication/apikey/_model_base.py, packages/cadl-python/test/generated/dev-driven/resiliency/devdriven/_model_base.py, packages/cadl-python/test/generated/dictionary/dictionary/_model_base.py, packages/cadl-python/test/generated/extensible-enums/extensibleenums/_model_base.py, packages/cadl-python/test/generated/hello/hello/_model_base.py, packages/cadl-python/test/generated/inheritance/models/inheritance/_model_base.py, packages/cadl-python/test/generated/item-types/arrays/itemtypes/_model_base.py, packages/cadl-python/test/generated/lro-basic/azure/lro/_model_base.py, packages/cadl-python/test/generated/oauth2/authentication/oauth2/_model_base.py, packages/cadl-python/test/generated/property-optional/models/property/optional/_model_base.py, packages/cadl-python/test/generated/property-types/models/property/types/_model_base.py, packages/cadl-python/test/generated/readonly-properties/readonlyproperties/_model_base.py, packages/cadl-python/test/generated/special-words/specialwords/_model_base.py, packages/cadl-python/test/generated/srv-driven-1/resiliency/servicedriven1/_model_base.py, packages/cadl-python/test/generated/srv-driven-2/resiliency/servicedriven2/_model_base.py, packages/cadl-python/test/generated/usage/models/usage/_model_base.py, packages/cadl-python/test/mock_api_tests/asynctests/test_property_types_async.py, packages/cadl-python/test/mock_api_tests/test_property_types.py
1.fix sub model deserialization
2. fix paging deserialization
=> fix submodel deserialization

packages/cadl-python/src/emitter.ts
This PR generate cadl union at https://github.com/Azure/azure-rest-api-specs/blob/feature/cognitiveservices/openai-cadl/specification/cognitiveservices/OpenAI.Inference/models/embeddings.create.cadl#L22
like below:
=> generate CombinedType

packages/cadl-python/src/emitter.ts
=> fix folder writing for cadl-output

packages/cadl-python/src/emitter.ts, packages/cadl-python/test/generated/visibility/models/visibility/automatic/models/_models.py, packages/cadl-python/test/mock_api_tests/asynctests/test_visibility_async.py, packages/cadl-python/test/mock_api_tests/test_visibility.py
Update the code to only put "readOnly" on "read" visibility. This allows the test in CADL Ranch to pass.
=> Visibility tests

eng/pipelines/internal-ci.yml
reference PR: https://github.com/Azure/autorest.typescript/pull/1710
e-mail: "RE: Cadl Ranch CI changes"
=> update coverage account name

packages/autorest.python/autorest/codegen/templates/model_base.py.jinja2, packages/cadl-python/test/generated/api-key/authentication/apikey/_model_base.py, packages/cadl-python/test/generated/dev-driven/resiliency/devdriven/_model_base.py, packages/cadl-python/test/generated/dictionary/dictionary/_model_base.py, packages/cadl-python/test/generated/extensible/enums/extensible/_model_base.py, packages/cadl-python/test/generated/fixed/enums/fixed/_model_base.py, packages/cadl-python/test/generated/hello/hello/_model_base.py, packages/cadl-python/test/generated/inheritance/models/inheritance/_model_base.py, packages/cadl-python/test/generated/item-types/arrays/itemtypes/_model_base.py, packages/cadl-python/test/generated/lro-basic/azure/lro/_model_base.py, packages/cadl-python/test/generated/oauth2/authentication/oauth2/_model_base.py, packages/cadl-python/test/generated/property-optional/models/property/optional/_model_base.py, packages/cadl-python/test/generated/property-types/models/property/types/_model_base.py, packages/cadl-python/test/generated/special-words/specialwords/_model_base.py, packages/cadl-python/test/generated/srv-driven-1/resiliency/servicedriven1/_model_base.py, packages/cadl-python/test/generated/srv-driven-2/resiliency/servicedriven2/_model_base.py, packages/cadl-python/test/generated/union/authentication/union/_model_base.py, packages/cadl-python/test/generated/usage/models/usage/_model_base.py, packages/cadl-python/test/generated/visibility/models/visibility/automatic/_model_base.py
fix for tests https://github.com/Azure/azure-sdk-for-python/blob/version_tolerant_models/sdk/core/azure-core/tests/test_serialization_models.py
=> fix model_base.py with azure-core tests

packages/autorest.python/ChangeLog.md, packages/autorest.python/autorest/codegen/models/base_builder.py, packages/autorest.python/autorest/codegen/serializers/builder_serializer.py, packages/autorest.python/autorest/m4reformatter/__init__.py, packages/autorest.python/test/vanilla/legacy/Expected/AcceptanceTests/ModelFlattening/modelflattening/aio/operations/_auto_rest_resource_flattening_test_service_operations.py, packages/autorest.python/test/vanilla/legacy/Expected/AcceptanceTests/ModelFlattening/modelflattening/operations/_auto_rest_resource_flattening_test_service_operations.py, packages/autorest.python/test/vanilla/version-tolerant/Expected/AcceptanceTests/ModelFlatteningVersionTolerant/modelflatteningversiontolerant/_operations/_operations.py, packages/autorest.python/test/vanilla/version-tolerant/Expected/AcceptanceTests/ModelFlatteningVersionTolerant/modelflatteningversiontolerant/aio/_operations/_operations.py
=> show externalDocs in doc

packages/autorest.python/autorest/codegen/models/__init__.py, packages/autorest.python/autorest/codegen/serializers/builder_serializer.py
effect: https://github.com/Azure/autorest.python/commit/8c8c7e6af5383a1522f15150594da3f1f1297868
related PR:https://github.com/Azure/autorest.python/pull/1684
=> raise TypeError if method signature is `_Unset`

docs/client/initializing.md, docs/client/models.md, docs/client/operations.md, docs/client/readme.md, docs/faq.md, docs/generate/directives.md, docs/generate/multiapi.md, docs/generate/readme.md, docs/migrate/readme.md, docs/readme.md, docs/troubleshooting.md, eng/pipelines/ci.yml, eng/pipelines/internal-ci.yml, packages/autorest.python/ChangeLog.md, packages/autorest.python/README.md, packages/autorest.python/package.json, packages/autorest.python/samples/readme.md
This is mainly to make pipeline runnable (like https://github.com/Azure/autorest.python/pull/1687) after we change branch name.
=> autorestv3 --> main

.github/dependabot.yml, eng/requirements.txt, packages/autorest.python/dev_requirements.txt, packages/autorest.python/test/azure/version-tolerant/tox.ini, packages/autorest.python/test/dpg/version-tolerant/tox.ini, packages/autorest.python/test/vanilla/version-tolerant/tox.ini, packages/cadl-python/dev_requirements.txt, packages/cadl-python/test/tox.ini
This should simplify the life of dependabot updates to all environments of the repository
=> Refactor dependencies for CI

packages/autorest.python/autorest/black/__init__.py
don't want to fail on black trying to read files it can't
=> don't fail if black can't read file

packages/cadl-python/test/mock_api_tests/asynctests/test_core_async.py, packages/cadl-python/test/mock_api_tests/test_core.py, packages/cadl-python/test/requirements.txt
https://github.com/Azure/autorest.python/issues/1461
=> add test for cadl-azure-core

.vscode/launch.json, eng/pipelines/ci-template.yml, eng/pipelines/ci.yml, eng/pipelines/internal-ci.yml, package.json, packages/autorest.python/autorest/m4reformatter/__init__.py, packages/autorest.python/autorest/preprocess/__init__.py, packages/cadl-python/.eslintrc.cjs, packages/cadl-python/package.json, packages/cadl-python/src/emitter.ts, packages/cadl-python/src/external-process.ts, packages/cadl-python/src/index.ts, packages/cadl-python/src/lib.ts, packages/cadl-python/tasks.py, packages/cadl-python/test/generated/collectionFormat/collectionformat/_operations/_operations.py, packages/cadl-python/test/generated/collectionFormat/collectionformat/aio/_operations/_operations.py, packages/cadl-python/test/generated/core/_specs_/azure/core/_operations/_operations.py, packages/cadl-python/test/generated/core/_specs_/azure/core/aio/_operations/_operations.py, packages/cadl-python/test/generated/core/_specs_/azure/core/models/_models.py, packages/cadl-python/test/generated/dev-driven/resiliency/devdriven/_operations/_operations.py, packages/cadl-python/test/generated/dev-driven/resiliency/devdriven/aio/_operations/_operations.py, packages/cadl-python/test/generated/dev-driven/resiliency/devdriven/models/_models.py, packages/cadl-python/test/generated/traits/_specs_/azure/traits/models/_models.py, pnpm-lock.yaml
will be red until release of @azure-tools/typespec-client-generator-core on monday
=> bump to typespec packages

packages/typespec-python/test/mock_api_tests/asynctests/test_collection_format_async.py, packages/typespec-python/test/mock_api_tests/test_collection_format.py, packages/typespec-python/test/requirements.txt
Part of https://github.com/Azure/autorest.python/issues/1461.
=> Add test for collection format

packages/autorest.python/ChangeLog.md, packages/autorest.python/autorest/codegen/__init__.py, packages/autorest.python/autorest/codegen/templates/packaging_templates/setup.py.jinja2, packages/autorest.python/test/azure/legacy/Expected/AcceptanceTests/PackageModeBatch/setup.py, packages/autorest.python/test/azure/legacy/Expected/AcceptanceTests/PackageModeDataPlane/setup.py, packages/autorest.python/test/azure/legacy/Expected/AcceptanceTests/PackageModeMgmtPlane/setup.py, packages/autorest.python/test/vanilla/legacy/Expected/AcceptanceTests/PackageModeDataPlane/setup.py, packages/typespec-python/CHANGELOG.md, packages/typespec-python/src/lib.ts, packages/typespec-python/tasks.py, packages/typespec-python/test/generated/hello/CHANGELOG.md, packages/typespec-python/test/generated/hello/LICENSE, packages/typespec-python/test/generated/hello/MANIFEST.in, packages/typespec-python/test/generated/hello/README.md, packages/typespec-python/test/generated/hello/dev_requirements.txt, packages/typespec-python/test/generated/hello/setup.py
https://github.com/Azure/autorest.python/issues/1834
=> support package-pprint-name for typespec

packages/autorest.python/ChangeLog.md, packages/autorest.python/autorest/codegen/serializers/builder_serializer.py
https://github.com/Azure/autorest.python/issues/1835
=> Xml optimize

packages/typespec-python/CHANGELOG.md, packages/typespec-python/src/emitter.ts
Resolve #1805.
I don't know whether we need to add cadl-ranch test for this (though I did it locally) since it is not encouraged to use object type. Any thoughts?
=> generate all kinds of empty model with any

eng/pipelines/ci-template.yml, eng/pipelines/nightly.yml, eng/scripts/check-for-changed-files.js, package.json
=> add nightly run for latest tsp packages 

packages/typespec-python/package.json, packages/typespec-python/test/generated/azure-client-generator-core-internal/_specs_/azure/clientgenerator/core/internal/aio/operations/_operations.py, packages/typespec-python/test/generated/azure-client-generator-core-internal/_specs_/azure/clientgenerator/core/internal/models/_models.py, packages/typespec-python/test/generated/azure-client-generator-core-internal/_specs_/azure/clientgenerator/core/internal/operations/_operations.py, packages/typespec-python/test/mock_api_tests/asynctests/test_azure_core_traits_async.py, packages/typespec-python/test/mock_api_tests/test_azure_core_traits.py, pnpm-lock.yaml
=> upgrade cadl-ranch version

packages/autorest.python/autorest/codegen/templates/model_base.py.jinja2, packages/typespec-python/test/generated/authentication-api-key/authentication/apikey/_model_base.py, packages/typespec-python/test/generated/authentication-oauth2/authentication/oauth2/_model_base.py, packages/typespec-python/test/generated/authentication-union/authentication/union/_model_base.py, packages/typespec-python/test/generated/azure-client-generator-core-internal/_specs_/azure/clientgenerator/core/internal/_model_base.py, packages/typespec-python/test/generated/azure-core-basic/_specs_/azure/core/basic/_model_base.py, packages/typespec-python/test/generated/azure-core-lro-rpc/_specs_/azure/core/lro/rpc/_model_base.py, packages/typespec-python/test/generated/azure-core-lro-standard/_specs_/azure/core/lro/standard/_model_base.py, packages/typespec-python/test/generated/azure-core-traits/_specs_/azure/core/traits/_model_base.py, packages/typespec-python/test/generated/parameters-collection-format/parameters/collectionformat/_model_base.py, packages/typespec-python/test/generated/parameters-spread/parameters/spread/_model_base.py, packages/typespec-python/test/generated/projection-projected-name/projection/projectedname/_model_base.py, packages/typespec-python/test/generated/resiliency-srv-driven1/resiliency/srv/driven1/_model_base.py, packages/typespec-python/test/generated/resiliency-srv-driven2/resiliency/srv/driven2/_model_base.py, packages/typespec-python/test/generated/server-path-multiple/server/path/multiple/_model_base.py, packages/typespec-python/test/generated/server-path-single/server/path/single/_model_base.py, packages/typespec-python/test/generated/special-words/specialwords/_model_base.py, packages/typespec-python/test/generated/typetest-array/typetest/array/_model_base.py, packages/typespec-python/test/generated/typetest-dictionary/typetest/dictionary/_model_base.py, packages/typespec-python/test/generated/typetest-enum-extensible/typetest/enum/extensible/_model_base.py, packages/typespec-python/test/generated/typetest-enum-fixed/typetest/enum/fixed/_model_base.py, packages/typespec-python/test/generated/typetest-model-inheritance/typetest/model/inheritance/_model_base.py, packages/typespec-python/test/generated/typetest-model-usage/typetest/model/usage/_model_base.py, packages/typespec-python/test/generated/typetest-model-visibility/typetest/model/visibility/_model_base.py, packages/typespec-python/test/generated/typetest-property-nullable/typetest/property/nullable/_model_base.py, packages/typespec-python/test/generated/typetest-property-optional/typetest/property/optional/_model_base.py, packages/typespec-python/test/generated/typetest-property-valuetypes/typetest/property/valuetypes/_model_base.py, packages/typespec-python/test/generated/typetest-union/typetest/union/_model_base.py
=> pylint disable type prop warnings

packages/typespec-python/CHANGELOG.md, packages/typespec-python/src/emitter.ts
fix: https://github.com/Azure/autorest.python/issues/1917
=> do generate user defined empty model

packages/autorest.python/autorest/codegen/models/operation.py, packages/autorest.python/autorest/codegen/models/request_builder_parameter.py, packages/typespec-python/test/generated/azure-client-generator-core-internal/_specs_/azure/clientgenerator/core/internal/aio/operations/_operations.py, packages/typespec-python/test/generated/azure-client-generator-core-internal/_specs_/azure/clientgenerator/core/internal/operations/_operations.py, packages/typespec-python/test/generated/typetest-enum-extensible/typetest/enum/extensible/_operations/_operations.py, packages/typespec-python/test/generated/typetest-enum-fixed/typetest/enum/fixed/_operations/_operations.py
fix https://github.com/Azure/autorest.python/issues/1918
=> Fix pylint/mypy

packages/autorest.python/ChangeLog.md, packages/autorest.python/autorest/codegen/serializers/__init__.py, packages/autorest.python/autorest/codegen/serializers/sample_serializer.py, packages/autorest.python/autorest/codegen/serializers/utils.py
fix https://github.com/Azure/autorest.python/issues/1916, https://github.com/Azure/autorest.python/issues/1920
=> Fix `--generate-samples` for resources, rdbms and confidentialledger

packages/typespec-python/CHANGELOG.md, packages/typespec-python/package.json, packages/typespec-python/src/emitter.ts, packages/typespec-python/test/generated/encode-duration/encode/duration/_client.py, packages/typespec-python/test/generated/encode-duration/encode/duration/aio/_client.py, packages/typespec-python/test/generated/encode-duration/encode/duration/aio/operations/__init__.py, packages/typespec-python/test/generated/encode-duration/encode/duration/aio/operations/_operations.py, packages/typespec-python/test/generated/encode-duration/encode/duration/models/__init__.py, packages/typespec-python/test/generated/encode-duration/encode/duration/models/_models.py, packages/typespec-python/test/generated/encode-duration/encode/duration/operations/__init__.py, packages/typespec-python/test/generated/encode-duration/encode/duration/operations/_operations.py, packages/typespec-python/test/generated/server-path-multiple/server/path/multiple/models/_enums.py, packages/typespec-python/test/generated/typetest-enum-extensible/typetest/enum/extensible/models/_enums.py, packages/typespec-python/test/generated/typetest-enum-fixed/typetest/enum/fixed/models/_enums.py, packages/typespec-python/test/mock_api_tests/asynctests/test_encode_duration_async.py, packages/typespec-python/test/mock_api_tests/test_encode_duration.py, pnpm-lock.yaml
1. depend on the fix of https://github.com/Azure/typespec-azure/pull/3027
2. also depend on the cadl-ranch test case of https://github.com/Azure/cadl-ranch/pull/332
=> add test for encode

packages/autorest.python/ChangeLog.md, packages/autorest.python/autorest/m4reformatter/__init__.py, packages/autorest.python/test/vanilla/legacy/AcceptanceTests/test_constants.py, packages/autorest.python/test/vanilla/legacy/Expected/AcceptanceTests/Constants/constants/models/_models_py3.py
fix https://github.com/Azure/autorest.python/issues/1936
=> fix `x-ms-client-default`

packages/typespec-python/tasks.py
prepare for https://github.com/Azure/cadl-ranch/pull/334
=>  compatible with client.tsp

eng/pipelines/ci-template.yml, eng/pipelines/nightly.yml
run result: https://dev.azure.com/azure-sdk/public/_build/results?buildId=2818433&view=results
=> fix for #1959

packages/typespec-python/tasks.py
introduced in https://github.com/Azure/autorest.python/pull/1957
=> fix regeneration issue

packages/typespec-python/CHANGELOG.md, packages/typespec-python/src/emitter.ts, packages/typespec-python/test/generated/projection-projected-name/projection/projectedname/aio/operations/_operations.py, packages/typespec-python/test/generated/projection-projected-name/projection/projectedname/operations/_operations.py, packages/typespec-python/test/mock_api_tests/asynctests/test_projection_projected_name_async.py, packages/typespec-python/test/mock_api_tests/test_projection_projected_name.py
https://github.com/Azure/autorest.python/issues/2006
=> fix `@projectedName` for query parameter

packages/autorest.python/ChangeLog.md, packages/autorest.python/autorest/multiapi/__init__.py
https://github.com/Azure/azure-sdk-for-python/issues/31289
=> [multiapi] don't delete models/operations by default

packages/typespec-python/tasks.py, packages/typespec-python/test/unittests/generated/model_base.py, packages/typespec-python/test/unittests/test_model_base_serialization.py
=> add unit test for version tolerant model

packages/autorest.python/autorest/codegen/models/code_model.py, packages/typespec-python/CHANGELOG.md
https://github.com/Azure/autorest.python/issues/2056
=> Fix `_vendor.py`

packages/typespec-python/CHANGELOG.md, packages/typespec-python/src/emitter.ts
fix https://github.com/Azure/autorest.python/issues/2083
=> datetime fix in response header

packages/typespec-python/package.json, packages/typespec-python/src/emitter.ts, packages/typespec-python/test/generated/azure-client-generator-core-access/_specs_/azure/clientgenerator/core/access/aio/operations/_operations.py, packages/typespec-python/test/generated/azure-client-generator-core-access/_specs_/azure/clientgenerator/core/access/operations/_operations.py, packages/typespec-python/test/mock_api_tests/asynctests/test_azure_client_generator_core_access_async.py, packages/typespec-python/test/mock_api_tests/test_azure_client_generator_core_access.py, pnpm-lock.yaml
1. Complete access feature support
2. Add access test case
3. Use lro meta data to get LRO logical result path
=> Access and LRO

.vscode/launch.json, packages/autorest.python/autorest/m4reformatter/__init__.py, packages/autorest.python/autorest/preprocess/__init__.py, packages/autorest.python/test/azure/legacy/AcceptanceTests/asynctests/test_parameter.py, packages/autorest.python/test/azure/legacy/AcceptanceTests/test_azure_url.py, packages/autorest.python/test/azure/legacy/AcceptanceTests/test_parameter.py, packages/autorest.python/test/azure/version-tolerant/AcceptanceTests/asynctests/test_parameter.py, packages/autorest.python/test/azure/version-tolerant/AcceptanceTests/test_parameter.py, packages/autorest.python/test/azure/version-tolerant/Expected/AcceptanceTests/AzureSpecialsVersionTolerant/azurespecialpropertiesversiontolerant/_client.py, packages/autorest.python/test/azure/version-tolerant/Expected/AcceptanceTests/AzureSpecialsVersionTolerant/azurespecialpropertiesversiontolerant/_configuration.py, packages/autorest.python/test/azure/version-tolerant/Expected/AcceptanceTests/AzureSpecialsVersionTolerant/azurespecialpropertiesversiontolerant/aio/_client.py, packages/autorest.python/test/azure/version-tolerant/Expected/AcceptanceTests/AzureSpecialsVersionTolerant/azurespecialpropertiesversiontolerant/aio/_configuration.py, packages/autorest.python/test/azure/version-tolerant/Expected/AcceptanceTests/StorageManagementClientVersionTolerant/storageversiontolerant/_client.py, packages/autorest.python/test/azure/version-tolerant/Expected/AcceptanceTests/StorageManagementClientVersionTolerant/storageversiontolerant/_configuration.py, packages/autorest.python/test/azure/version-tolerant/Expected/AcceptanceTests/StorageManagementClientVersionTolerant/storageversiontolerant/aio/_client.py, packages/autorest.python/test/azure/version-tolerant/Expected/AcceptanceTests/StorageManagementClientVersionTolerant/storageversiontolerant/aio/_configuration.py, packages/autorest.python/test/azure/version-tolerant/Expected/AcceptanceTests/SubscriptionIdApiVersionVersionTolerant/subscriptionidapiversionversiontolerant/_client.py, packages/autorest.python/test/azure/version-tolerant/Expected/AcceptanceTests/SubscriptionIdApiVersionVersionTolerant/subscriptionidapiversionversiontolerant/_configuration.py, packages/autorest.python/test/azure/version-tolerant/Expected/AcceptanceTests/SubscriptionIdApiVersionVersionTolerant/subscriptionidapiversionversiontolerant/aio/_client.py, packages/autorest.python/test/azure/version-tolerant/Expected/AcceptanceTests/SubscriptionIdApiVersionVersionTolerant/subscriptionidapiversionversiontolerant/aio/_configuration.py, packages/typespec-python/src/emitter.ts, packages/typespec-python/src/types.ts, packages/typespec-python/tasks.py, packages/typespec-python/test/generated/azure-mgmt-spheremsrest/CHANGELOG.md, packages/typespec-python/test/generated/azure-mgmt-spheremsrest/LICENSE, packages/typespec-python/test/generated/azure-mgmt-spheremsrest/MANIFEST.in, packages/typespec-python/test/generated/azure-mgmt-spheremsrest/README.md, packages/typespec-python/test/generated/azure-mgmt-spheremsrest/dev_requirements.txt, packages/typespec-python/test/generated/azure-mgmt-spheremsrest/setup.py
=> update dpg generation from swagger to also maintain old client parameter ordering

packages/typespec-python/package.json, packages/typespec-python/src/emitter.ts, packages/typespec-python/src/types.ts, pnpm-lock.yaml
depend on: https://github.com/Azure/typespec-azure/pull/3718 to change to dev version
=> use emit context to get models mode

packages/typespec-python/CHANGELOG.md, packages/typespec-python/package.json, packages/typespec-python/src/emitter.ts
=> allow none models mode

packages/autorest.python/ChangeLog.md, packages/autorest.python/autorest/preprocess/__init__.py, packages/autorest.python/package.json, packages/typespec-python/CHANGELOG.md
=> only add json body overload if generating with models

packages/autorest.python/autorest/codegen/models/primitive_types.py, packages/typespec-python/test/azure/generated/azure-core-traits/specs/azure/core/traits/_operations/_operations.py, packages/typespec-python/test/azure/generated/azure-core-traits/specs/azure/core/traits/aio/_operations/_operations.py, packages/typespec-python/test/azure/generated/special-headers-conditional-request/specialheaders/conditionalrequest/_operations/_operations.py, packages/typespec-python/test/azure/generated/special-headers-conditional-request/specialheaders/conditionalrequest/aio/_operations/_operations.py, packages/typespec-python/test/unbranded/generated/special-headers-conditional-request/specialheaders/conditionalrequest/_operations/_operations.py, packages/typespec-python/test/unbranded/generated/special-headers-conditional-request/specialheaders/conditionalrequest/aio/_operations/_operations.py
fix https://teams.microsoft.com/l/message/19:b97d98e6d22c41e0970a1150b484d935@thread.skype/1698771697439?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=3e17dcb0-4257-4a30-b843-77f47f1d4121&parentMessageId=1698771697439&teamName=Azure%20SDK&channelName=Language%20-%20Python&createdTime=1698771697439
=> fix docstring for `match_condition`

packages/typespec-python/CHANGELOG.md, packages/typespec-python/package.json, packages/typespec-python/src/types.ts, packages/typespec-python/test/azure/generated/parameters-spread/parameters/spread/aio/operations/_operations.py, packages/typespec-python/test/azure/generated/parameters-spread/parameters/spread/models/__init__.py, packages/typespec-python/test/azure/generated/parameters-spread/parameters/spread/models/_models.py, packages/typespec-python/test/azure/generated/parameters-spread/parameters/spread/operations/_operations.py, packages/typespec-python/test/generic_mock_api_tests/asynctests/test_parameters_spread_async.py, packages/typespec-python/test/generic_mock_api_tests/test_parameters_spread.py, packages/typespec-python/test/unbranded/generated/parameters-spread/parameters/spread/aio/operations/_operations.py, packages/typespec-python/test/unbranded/generated/parameters-spread/parameters/spread/models/__init__.py, packages/typespec-python/test/unbranded/generated/parameters-spread/parameters/spread/models/_models.py, packages/typespec-python/test/unbranded/generated/parameters-spread/parameters/spread/operations/_operations.py
1. auth basic/bearer first letter casing
2. list with anonymous model json payload flag
=> Fix emitter issue when generating openai

packages/typespec-python/CHANGELOG.md, packages/typespec-python/package.json, packages/typespec-python/src/types.ts, packages/typespec-python/test/azure/generated/typetest-model-enumdiscriminator/typetest/model/enumdiscriminator/models/_models.py, packages/typespec-python/test/azure/generated/typetest-model-nesteddiscriminator/typetest/model/nesteddiscriminator/models/_models.py, packages/typespec-python/test/generic_mock_api_tests/asynctests/test_typetest_model_inheritance_enum_discriminator_async.py, packages/typespec-python/test/generic_mock_api_tests/asynctests/test_typetest_model_inheritance_nested_discriminator_async.py, packages/typespec-python/test/generic_mock_api_tests/test_typetest_model_inheritance_enum_discriminator.py, packages/typespec-python/test/generic_mock_api_tests/test_typetest_model_inheritance_nested_discriminator.py, packages/typespec-python/test/unbranded/generated/typetest-model-enumdiscriminator/typetest/model/enumdiscriminator/models/_models.py, packages/typespec-python/test/unbranded/generated/typetest-model-nesteddiscriminator/typetest/model/nesteddiscriminator/models/_models.py
fixes https://github.com/Azure/autorest.python/issues/2270
=> fix enum discriminator

packages/typespec-python/CHANGELOG.md, packages/typespec-python/src/emitter.ts
fixes https://github.com/Azure/autorest.python/issues/2273
https://github.com/Azure/cadl-ranch/pull/445
=> fix body parameter type

packages/autorest.python/autorest/codegen/models/operation.py, packages/autorest.python/autorest/codegen/serializers/builder_serializer.py, packages/autorest.python/autorest/codegen/serializers/general_serializer.py, packages/autorest.python/autorest/codegen/templates/vendor.py.jinja2, packages/typespec-python/test/azure/generated/payload-multipart/payload/multipart/_vendor.py, packages/typespec-python/test/azure/generated/payload-multipart/payload/multipart/aio/operations/_operations.py, packages/typespec-python/test/azure/generated/payload-multipart/payload/multipart/operations/_operations.py, packages/typespec-python/test/generic_mock_api_tests/asynctests/test_payload_multipart_async.py, packages/typespec-python/test/generic_mock_api_tests/test_payload_multipart.py, packages/typespec-python/test/unbranded/generated/payload-multipart/payload/multipart/_vendor.py, packages/typespec-python/test/unbranded/generated/payload-multipart/payload/multipart/aio/operations/_operations.py, packages/typespec-python/test/unbranded/generated/payload-multipart/payload/multipart/operations/_operations.py
https://github.com/Azure/cadl-ranch/pull/460
=> support json part for multipart/form-data

packages/autorest.python/ChangeLog.md, packages/autorest.python/autorest/codegen/templates/enum.py.jinja2, packages/autorest.python/package.json, packages/autorest.python/test/vanilla/legacy/Expected/AcceptanceTests/ExtensibleEnums/extensibleenumsswagger/models/_pet_store_inc_enums.py, packages/typespec-python/CHANGELOG.md, packages/typespec-python/package.json
=> fix wrap enum value comments

packages/autorest.python/test/vanilla/version-tolerant/Expected/AcceptanceTests/MediaTypesVersionTolerant/mediatypesversiontolerant/_operations/_patch.py, packages/autorest.python/test/vanilla/version-tolerant/Expected/AcceptanceTests/MediaTypesVersionTolerant/mediatypesversiontolerant/aio/_operations/_patch.py
part fix of https://github.com/Azure/autorest.python/issues/2363
=> [lint] fix for _patch

packages/typespec-python/test/generic_mock_api_tests/test_typetest_property_valuetypes.py
add test for merged PR https://github.com/Azure/autorest.python/pull/2399
=> Add test for PR `order union deserialization so str is last option`

packages/autorest.python/autorest/codegen/serializers/builder_serializer.py, packages/typespec-python/test/azure/generated/encode-bytes/encode/bytes/aio/operations/_operations.py, packages/typespec-python/test/azure/generated/encode-bytes/encode/bytes/operations/_operations.py, packages/typespec-python/test/azure/generated/payload-content-negotiation/payload/contentnegotiation/aio/operations/_operations.py, packages/typespec-python/test/azure/generated/payload-content-negotiation/payload/contentnegotiation/operations/_operations.py, packages/typespec-python/test/generic_mock_api_tests/asynctests/test_encode_bytes_async.py, packages/typespec-python/test/generic_mock_api_tests/asynctests/test_payload_content_negotiation_async.py, packages/typespec-python/test/generic_mock_api_tests/test_encode_bytes.py, packages/typespec-python/test/generic_mock_api_tests/test_payload_content_negotiation.py, packages/typespec-python/test/unbranded/generated/encode-bytes/encode/bytes/aio/operations/_operations.py, packages/typespec-python/test/unbranded/generated/encode-bytes/encode/bytes/operations/_operations.py, packages/typespec-python/test/unbranded/generated/payload-content-negotiation/payload/contentnegotiation/aio/operations/_operations.py, packages/typespec-python/test/unbranded/generated/payload-content-negotiation/payload/contentnegotiation/operations/_operations.py
fixes https://github.com/Azure/autorest.python/issues/2415
=> fix `stream` for binary response type

eng/pipelines/ci.yml, packages/autorest.python/prepare.py, packages/autorest.python/start.py, packages/autorest.python/test/azure/legacy/tox.ini, packages/autorest.python/test/azure/version-tolerant/tox.ini, packages/autorest.python/test/dpg/version-tolerant/tox.ini, packages/autorest.python/test/multiapi/tox.ini, packages/autorest.python/test/unittests/tox.ini, packages/autorest.python/test/vanilla/legacy/tox.ini, packages/autorest.python/test/vanilla/version-tolerant/tox.ini, packages/typespec-python/test/azure/tox.ini, packages/typespec-python/test/unbranded/tox.ini
fixes https://github.com/Azure/autorest.python/issues/2451
=> check py38 in pipeline

packages/typespec-python/test/azure/generated/typetest-array/README.md
fixed misspelled word in generated READMEs #2436
=> Fix Misspelled word in generated READMEs

packages/autorest.python/autorest/codegen/templates/packaging_templates/README.md.jinja2
fixes https://github.com/Azure/autorest.python/issues/2436
=> fix misspelled word in README

.github/workflows/prepare-auto-release-branch.yml
Try to fix Github action https://github.com/Azure/autorest.python/actions/runs/8865784555/job/24342428427
Re: `pnpm chronus version` fail
=> add env var for github action 

.chronus/changes/fix_models_only-2024-5-11-21-50-18.md, packages/autorest.python/autorest/codegen/models/client.py, packages/autorest.python/autorest/preprocess/__init__.py
=> generate sdks that are models only

.chronus/changes/support-uri-2024-6-1-15-37-1.md, packages/typespec-python/src/types.ts
fixes https://github.com/Azure/autorest.python/issues/2662
=> Support uri

eng/scripts/sdk_regenerate.py
1. sort generation result to reduce useless diff
2. update git logic to make sure PR from main branch only has one commit to avoid useless history commit
=> [sdk regeneration pipeline] optimize

.chronus/changes/sdk-regen-optimization-2024-6-11-14-58-58.md, eng/scripts/sdk_regenerate.py, packages/typespec-python/generator/pygen/codegen/models/client.py, packages/typespec-python/generator/pygen/preprocess/__init__.py, packages/typespec-python/generator/pygen/utils.py
for https://github.com/Azure/azure-sdk-for-python/issues/36416
=> Fix import when method name is reserved word

.chronus/changes/fix_package_version-2024-6-12-15-20-17.md, packages/typespec-python/generator/pygen/codegen/__init__.py
=> make sure package version is a string

eng/dev_requirements.txt, packages/autorest.python/requirements.txt
release pipeline fails for https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3992502&view=logs&j=19992227-62fb-5b50-4e29-3b72bd33eea1&t=a09397dc-089b-5c2b-27b0-05598af03d57
I find an answer in https://github.com/pypa/setuptools/issues/4478 and hope to fix it.
=> fix release pipeline

.chronus/changes/fix-multipart-import-2024-6-29-16-22-46.md, packages/typespec-python/generator/pygen/codegen/models/operation.py
fix https://github.com/Azure/autorest.python/issues/2726
=> Fix multipart import

packages/typespec-python/package.json
supplement for https://github.com/Azure/autorest.python/pull/2723
=> bump 0.44.3

.chronus/changes/fix-sample-generation-2024-7-9-13-18-26.md, packages/typespec-python/src/http.ts
Fix sample generation for lro and paging operation
=> Fix sample generation for lro and paging operation

.chronus/changes/HEAD-2024-7-9-10-25-50.md, .chronus/changes/add_endpoint-2024-7-7-14-46-59.md, .chronus/changes/fix-sample-generation-2024-7-9-13-18-26.md, .chronus/changes/regen_script-2024-7-5-18-53-49.md, .chronus/changes/sample-tsp-2024-6-30-17-26-43.md, .chronus/changes/update-ci-template-2024-7-6-18-48-28.md, packages/autorest.python/CHANGELOG.md, packages/autorest.python/package.json, packages/typespec-python/CHANGELOG.md, packages/typespec-python/package.json
=> Release after bump 0.59.0 

.chronus/changes/fix-paging-2024-7-13-14-19-35.md, packages/autorest.python/autorest/m4reformatter/__init__.py
fix https://github.com/Azure/autorest.python/issues/2767
=> Fix crash when paging operation return type has parent type

eng/pipelines/generated-code-checks-template.yml
fix https://github.com/Azure/autorest.python/pull/2779/files#r1721184467
=> fix ci for apiview

.chronus/changes/fix-sample-generation-2024-2024-7-20-13-20-5.md, packages/typespec-python/generator/pygen/codegen/serializers/sample_serializer.py, packages/typespec-python/test/azure/generated/azure-example-basic/generated_samples/20221201preview/basic.py
fix https://github.com/Azure/autorest.python/issues/2783
=> Fix sample generation for keyword-only parameters

.chronus/changes/add-test-2024-7-8-18-12-59.md, .chronus/changes/add-testcase-2024-7-9-15-17-44.md, .chronus/changes/advanced-multipart-implementation-2024-7-13-12-56-54.md, .chronus/changes/bump-cadl-ranch-2024-7-12-15-47-49.md, .chronus/changes/fix-paging-2024-7-13-14-19-35.md, .chronus/changes/fix-sample-generation-2024-2024-7-20-13-20-5.md, .chronus/changes/node_tests-2024-7-15-16-1-36.md, .chronus/changes/npm_run_tests-2024-7-15-12-8-21.md, .chronus/changes/perf_model_base-2024-7-6-20-21-47.md, .chronus/changes/remove-sample-from-docstring-2024-7-15-15-33-37.md, .chronus/changes/update_59_1-2024-7-14-17-36-2.md, packages/autorest.python/CHANGELOG.md, packages/autorest.python/package.json, packages/typespec-python/CHANGELOG.md, packages/typespec-python/package.json
=> new release for 0.29.0

eng/pipelines/ci-template.yml
fix https://github.com/Azure/autorest.python/pull/2785#discussion_r1728109732
=> Remove outdated folder in CI

.chronus/changes/fix-nightly-2024-7-23-13-21-51.md, eng/pipelines/ci-template.yml, eng/pipelines/nightly.yml, packages/autorest.python/package.json, packages/typespec-python/package.json, packages/typespec-python/scripts/eng/format.ts, packages/typespec-python/scripts/eng/lint.ts, packages/typespec-python/scripts/eng/utils.ts
https://dev.azure.com/azure-sdk/public/_build/results?buildId=4074776&view=logs&j=ba1d0612-cf69-5eb7-e99b-b5534b1f542d&t=1a291d9e-f682-5778-7f3f-8efcde666b82
Latest dev version may introduce some deprecations so we shall skip to check the deprecation warnings:
=> fix nightly to skip deprecation warnings

packages/typespec-python/test/generic_mock_api_tests/asynctests/test_special_headers_conditional_request_async.py, packages/typespec-python/test/generic_mock_api_tests/test_special_headers_conditional_request.py
pending on https://github.com/Azure/cadl-ranch/pull/708
=> test case for etag

.chronus/changes/HEAD-2024-8-10-14-24-45.md, packages/typespec-python/generator/pygen/codegen/serializers/model_serializer.py, packages/typespec-python/generator/pygen/codegen/templates/model_dpg.py.jinja2
fix https://github.com/Azure/autorest.python/issues/2826
=> Add pylint disable for "line-too-long" and "too-many-locals"

.chronus/changes/add-testcase-2024-8-11-16-36-42.md, .chronus/changes/bump-tsp-0.60.0-2024-8-11-14-27-33.md, .chronus/changes/fix-ci-2024-09-11-2024-8-11-18-28-34.md, .chronus/changes/fix-pylint-2024-09-12-2024-8-12-16-9-4.md, packages/autorest.python/CHANGELOG.md, packages/autorest.python/package.json, packages/typespec-python/CHANGELOG.md, packages/typespec-python/package.json
release for typespec-python 0.32.0 && autorest.python 6.22.0
=> release for typespec-python 0.32.0 && autorest.python 6.22.0

packages/typespec-python/test/generic_mock_api_tests/asynctests/test_payload_xml_async.py
fix missing test in this pr: https://github.com/Azure/autorest.python/pull/2806#discussion_r1749726627
=> add async test for xml

.chronus/changes/depend_on_typespec-2024-8-25-19-12-11.md, .chronus/changes/upgrade_cadl_ranch-2024-8-23-16-40-22.md, .chronus/changes/upgrade_tcgc-2024-8-25-16-11-25.md, packages/autorest.python/CHANGELOG.md, packages/autorest.python/package.json, packages/typespec-python/CHANGELOG.md, packages/typespec-python/package.json
release typespec-python 0.34.0 and autorest.python 6.24.0
=> release typespec-python 0.34.0 and autorest.python 6.24.0

.chronus/changes/awaitOnEmit-2024-9-7-13-52-44.md, packages/typespec-python/src/emitter.ts
fixes https://github.com/Azure/azure-sdk-tools/issues/9073
=> await call to onEmit

.chronus/changes/auto-bump-tsp-0.62.0-python-2024-10-6-15-9-55.md, .chronus/changes/auto-update-cadl-ranch-2024-9-30-10-15-17.md, .chronus/changes/dependabot_skip_check_changes-2024-9-29-10-2-41.md, .chronus/changes/update-package-2024-2024-9-31-9-52-24.md, .chronus/changes/update-package-2024-9-24-8-33-7.md, .chronus/changes/upgrade_tcgc-2024-10-5-14-24-3.md, packages/autorest.python/CHANGELOG.md, packages/autorest.python/package.json, packages/typespec-python/CHANGELOG.md, packages/typespec-python/package.json
new release for typespec-python 0.36.2 and autorest.python 6.26.2
=> new release for typespec-python 0.36.2 and autorest.python 6.26.2

.chronus/changes/auto-python-fix-access-2024-10-8-14-45-24.md, packages/autorest.python/package.json, packages/typespec-python/package.json, pnpm-lock.yaml
fix https://github.com/Azure/autorest.python/issues/2907
Auto PR for https://github.com/microsoft/typespec/pull/5020
=> Bump http-client-python 0.3.8 to fix access for paging/lro

.chronus/changes/auto-python-dep-2024-10-7-15-2-13.md, .chronus/changes/auto-python-fix-access-2024-10-8-14-45-24.md, packages/autorest.python/CHANGELOG.md, packages/autorest.python/package.json, packages/typespec-python/CHANGELOG.md, packages/typespec-python/package.json
release for typespec-python 0.36.3 and autorest.python 6.26.3
=> release for typespec-python 0.36.3 and autorest.python 6.26.3

.chronus/changes/auto-python-fix-string-2024-10-14-16-8-52.md, packages/autorest.python/CHANGELOG.md, packages/autorest.python/package.json, packages/typespec-python/CHANGELOG.md, packages/typespec-python/package.json, pnpm-lock.yaml
fix https://github.com/Azure/autorest.python/issues/2917
Auto PR for https://github.com/microsoft/typespec/pull/5111
=> Fix quote for string type then release new version

.chronus/changes/azure-flavor-2025-0-6-13-40-54.md, packages/typespec-python/src/emitter.ts
resolve: https://github.com/Azure/autorest.python/issues/2971
=> set flavor to azure if not set

.chronus/changes/fix-autorest.python-2025-0-8-11-30-42.md, packages/autorest.python/CHANGELOG.md, packages/autorest.python/package.json, packages/autorest.python/scripts/install.py
Fix install issue for autorest.python:
=> Fix install for autorest.python

.chronus/changes/add-testcases-2025-1-11-11-37-49.md, packages/typespec-python/test/azure/mock_api_tests/asynctests/test_azure_arm_operationtemplates_async.py, packages/typespec-python/test/azure/mock_api_tests/asynctests/test_azure_arm_resource_async.py, packages/typespec-python/test/azure/mock_api_tests/test_azure_arm_operationtemplates.py, packages/typespec-python/test/azure/mock_api_tests/test_azure_arm_resource.py, packages/typespec-python/test/azure/requirements.txt
Add testcases for several spector scenarios
=> [python] update testcases

.chronus/changes/msyyc-patch-1-2025-1-28-15-9-32.md, packages/typespec-python/package.json
fix https://github.com/microsoft/typespec/issues/6114
=> [typepsec-python] Update package.json with correct url

packages/autorest.python/package.json, packages/typespec-python/package.json, packages/typespec-python/test/azure/generated/client-namespace/client/clientnamespace/_operations/_operations.py, packages/typespec-python/test/azure/generated/client-namespace/client/clientnamespace/aio/_operations/_operations.py, packages/typespec-python/test/azure/generated/client-namespace/client/clientnamespace/second/_operations/_operations.py, packages/typespec-python/test/azure/generated/client-namespace/client/clientnamespace/second/aio/_operations/_operations.py, packages/typespec-python/test/azure/generated/client-namespace/client/clientnamespace/second/models/_models.py, packages/typespec-python/test/unbranded/generated/encode-duration/encode/duration/property/aio/operations/_operations.py, packages/typespec-python/test/unbranded/generated/encode-duration/encode/duration/property/operations/_operations.py, packages/typespec-python/test/unbranded/generated/encode-numeric/encode/numeric/property/aio/operations/_operations.py, packages/typespec-python/test/unbranded/generated/encode-numeric/encode/numeric/property/operations/_operations.py, packages/typespec-python/test/unbranded/generated/parameters-basic/parameters/basic/explicitbody/aio/operations/_operations.py, packages/typespec-python/test/unbranded/generated/parameters-basic/parameters/basic/explicitbody/operations/_operations.py, packages/typespec-python/test/unbranded/generated/parameters-spread/parameters/spread/model/aio/operations/_operations.py, packages/typespec-python/test/unbranded/generated/parameters-spread/parameters/spread/model/operations/_operations.py, packages/typespec-python/test/unbranded/generated/payload-content-negotiation/payload/contentnegotiation/differentbody/aio/operations/_operations.py, packages/typespec-python/test/unbranded/generated/payload-content-negotiation/payload/contentnegotiation/differentbody/operations/_operations.py, packages/typespec-python/test/unbranded/generated/payload-multipart/payload/multipart/formdata/aio/operations/_operations.py, packages/typespec-python/test/unbranded/generated/payload-multipart/payload/multipart/formdata/httpparts/nonstring/aio/operations/_operations.py, packages/typespec-python/test/unbranded/generated/payload-multipart/payload/multipart/formdata/httpparts/nonstring/operations/_operations.py, packages/typespec-python/test/unbranded/generated/payload-multipart/payload/multipart/formdata/operations/_operations.py, packages/typespec-python/test/unbranded/generated/serialization-encoded-name-json/serialization/encodedname/json/property/aio/operations/_operations.py, packages/typespec-python/test/unbranded/generated/serialization-encoded-name-json/serialization/encodedname/json/property/operations/_operations.py, packages/typespec-python/test/unbranded/generated/special-words/specialwords/modelproperties/aio/operations/_operations.py, packages/typespec-python/test/unbranded/generated/special-words/specialwords/modelproperties/operations/_operations.py, packages/typespec-python/test/unbranded/generated/special-words/specialwords/models/aio/operations/_operations.py, packages/typespec-python/test/unbranded/generated/special-words/specialwords/models/operations/_operations.py, pnpm-lock.yaml
Auto PR for https://github.com/microsoft/typespec/pull/7005
=> Fix docstring type for multi namespaces

packages/autorest.python/CHANGELOG.md, packages/autorest.python/package.json, packages/typespec-python/CHANGELOG.md, packages/typespec-python/package.json, pnpm-lock.yaml
Auto PR for https://github.com/microsoft/typespec/pull/7667
=> publish a new version

.chronus/changes/auto-microsoft-copilot-fix-7610-2025-5-25-8-46-53.md, .chronus/changes/copilot-fix-3106-2025-5-25-11-41-49.md, packages/autorest.python/CHANGELOG.md, packages/autorest.python/package.json, packages/typespec-python/CHANGELOG.md, packages/typespec-python/package.json, pnpm-lock.yaml
Auto PR for https://github.com/microsoft/typespec/pull/7757
=> bump typespec-python 0.45.4

.chronus/changes/add-testcases-08-20-2025-7-20-14-42-52.md, .chronus/changes/auto-iscai-msft-python-upgradeTyping-2025-7-8-13-50-30.md, .chronus/changes/auto-microsoft-cloud-setting-python-2025-7-19-14-9-20.md, .chronus/changes/auto-microsoft-fix-proproject.toml-2025-7-14-15-14-2.md, .chronus/changes/auto-microsoft-python-fix-optional-body-2025-7-22-10-56-50.md, .chronus/changes/auto-swathipil-http-client-python-move-azure-sdk-tools-dev-reqs-2025-7-26-9-46-12.md, .chronus/changes/copilot-fix-3187-2025-7-28-11-20-7.md, .chronus/changes/copilot-fix-3187-2025-7-28-15-20-11.md, .chronus/changes/upgrade_spector-2025-7-19-11-51-56.md, packages/autorest.python/CHANGELOG.md, packages/autorest.python/package.json, packages/typespec-python/CHANGELOG.md, packages/typespec-python/package.json, pnpm-lock.yaml
Auto PR for https://github.com/microsoft/typespec/pull/8321
=> [python] publish new version

.chronus/changes/sync-typespec-repo-2025-8-30-2-57-50.md, .chronus/changes/sync-typespec-repo-2025-8-30-2-58-11.md, packages/autorest.python/package.json, packages/typespec-python/package.json, pnpm-lock.yaml
bump dependency to sync with https://github.com/microsoft/typespec/pull/8381 and https://github.com/microsoft/typespec/pull/8607
=> Sync typespec repo
