test/vanilla/AcceptanceTests/form_data_tests.py
FYI @olydis , since 2.4.2 some tests switch from Content-Length to Transfer-Encoding: chunked, breaking the tests
=> Fix tests for testserver 2.4.2

README.md, package.json
This should let you get the code model from the new 'modeler four' 
Note! you're going to want to make sure you have the latest autorest beta ( `npm install -g @autorest/autorest` and `autorest-beta --reset` ) as it fixes the weird glitch when python is installed from the store.
=> Update to configuration to use modeler four

test/azure/AcceptanceTests/asynctests/test_lro.py, test/azure/AcceptanceTests/asynctests/test_paging.py, test/azure/AcceptanceTests/test_lro.py, test/vanilla/AcceptanceTests/asynctests/test_http.py, test/vanilla/AcceptanceTests/conftest.py, test/vanilla/AcceptanceTests/test_http.py
https://github.com/Azure/azure-sdk-for-python/pull/7777 requires to enable cookie fixture in async tests
=> Add cookie fixture to async tests

autorest/codegen/models/enum_schema.py, package.json, test/vanilla/Expected/AcceptanceTests/BodyComplex/bodycomplex/models/_auto_rest_complex_test_service_enums.py, test/vanilla/Expected/AcceptanceTests/BodyComplex/bodycomplex/models/_models.py, test/vanilla/Expected/AcceptanceTests/BodyComplex/bodycomplex/models/_models_py3.py, test/vanilla/Expected/AcceptanceTests/BodyDateTime/bodydatetime/aio/operations_async/_datetime_model_operations_async.py, test/vanilla/Expected/AcceptanceTests/BodyDateTime/bodydatetime/operations/_datetime_model_operations.py
fixes #113 
If multiple enums within an enum class have the same python name, we use the default yaml names for these enums instead.
=> Different enum generation

autorest/codegen/models/primitive_schemas.py
Python will not make a difference between char type and string type
See https://github.com/Azure/autorest.testserver/issues/131 too
=> Declare char as a type of string

README.md
Wait for the next build of autorest cli and autorest.core  before committing this.
The reason batch mode wasn't working (and a few other things) is because when you have settings in `python:` they are tied to the plugin `python` (and the dependent tasks get to share them)
In the new generator, you have multiple plugins, but none were named `python` 
This creates an empty `python` plugin (which just passes content straight thru), and makes `m2r` get the input from that one.
=> Fix to support python: settings

README.md
This should fix the problem with things where you have a user configuration file that looks like this:
~~~ markdown
``` yaml $(python)
python:
azure-arm: true
license-header: MICROSOFT_MIT_NO_VERSION
payload-flattening-threshold: 2
```
~~~
(ie https://github.com/Azure/autorest.modelerfour/issues/182) 
The reason this changes, is that in v2 generators, things like flattening were handled by the **common library,** and actually happened during the execution of the python generator, not in the modeler stage. Things that happened during the python generator, inherited configuration from the `python:`  settings section.  
Now, since the modelerfour/flattener handles that before the language-specific generator runs, the settings would either need to be changed to:
~~~ markdown
``` yaml …
```
=> Reorder pipeline so that `python:` settings load earlier

autorest/codegen/templates/metadata.json.jinja2, autorest/multiapi/__init__.py, autorest/multiapi/multiapi_serializer.py, autorest/multiapi/templates/multiapi_config.py.jinja2, autorest/multiapi/templates/multiapi_models.py.jinja2, autorest/multiapi/templates/multiapi_version.py.jinja2
- Use autorest to write, otherwise in some cases autorest quit before the Python cache wrote to disk
- "models.py" was missing
- "_version.py" should be written if there is none, so code is importable at least
- Configuration import missing
- Backport UserAgent work
=> Various fixes on multiapi script

autorest/codegen/models/code_model.py, package.json
fixes #466 
I've also ensured this fails with storage mgmt:
I also included an update to package.json in this pr to get the addition of the media types swagger.
=> Avoiding schema duplication using yaml ids instead of names

autorest/codegen/models/code_model.py
fixes #464 
Previously opened an [issue](https://github.com/Azure/autorest.modelerfour/issues/198) with modelerfour, determined this is not a bug and we should have a special case to deal with AnySchema.
Was causing an issue generating [this](https://github.com/Azure/azure-rest-api-specs/blob/58c68dea43b9924fedaf819bfead1bc922fe9143/specification/web/resource-manager/Microsoft.Web/stable/2016-09-01/AppServicePlans.json#L803), but now generating correctly
=> special case for AnySchema

eng/pipelines/publish-dev-release.yml
This change adds a new CI configuration that enables easy publishing of `@autorest/python` development releases to GitHub Releases.  The pipeline that runs this build configuration can be found here:
https://dev.azure.com/azure-sdk/internal/_build?definitionId=1600&_a=summary
It will need to be invoked manually on the `autorestv3` branch when a new release should be published.
=> Add CI configuration for publishing v5 development releases to GitHub

autorest/codegen/models/parameter.py, autorest/codegen/models/parameter_list.py, autorest/codegen/templates/operation.py.jinja2, test/vanilla/Expected/AcceptanceTests/BodyString/bodystring/aio/operations_async/_string_operations_async.py, test/vanilla/Expected/AcceptanceTests/BodyString/bodystring/operations/_string_operations.py, test/vanilla/Expected/AcceptanceTests/Http/httpinfrastructure/aio/operations_async/_http_client_failure_operations_async.py, test/vanilla/Expected/AcceptanceTests/Http/httpinfrastructure/aio/operations_async/_http_redirects_operations_async.py, test/vanilla/Expected/AcceptanceTests/Http/httpinfrastructure/aio/operations_async/_http_retry_operations_async.py, test/vanilla/Expected/AcceptanceTests/Http/httpinfrastructure/aio/operations_async/_http_server_failure_operations_async.py, test/vanilla/Expected/AcceptanceTests/Http/httpinfrastructure/aio/operations_async/_http_success_operations_async.py, test/vanilla/Expected/AcceptanceTests/Http/httpinfrastructure/operations/_http_client_failure_operations.py, test/vanilla/Expected/AcceptanceTests/Http/httpinfrastructure/operations/_http_redirects_operations.py, test/vanilla/Expected/AcceptanceTests/Http/httpinfrastructure/operations/_http_retry_operations.py, test/vanilla/Expected/AcceptanceTests/Http/httpinfrastructure/operations/_http_server_failure_operations.py, test/vanilla/Expected/AcceptanceTests/Http/httpinfrastructure/operations/_http_success_operations.py
fixes #447 
Adds optional constant params to signature if they will appear in function. Also ensure that the default value for these optional constants is their constant value.
=> Optional constant params in signature

README.md
Added because there was an enum-model name collision in storage 2016-12 (had a [model](https://github.com/Azure/azure-rest-api-specs/blob/884245893e9f85bd499369091650695c33835687/specification/storage/resource-manager/Microsoft.Storage/stable/2016-12-01/storage.json#L1057) and [enum](https://github.com/Azure/azure-rest-api-specs/blob/884245893e9f85bd499369091650695c33835687/specification/storage/resource-manager/Microsoft.Storage/stable/2016-12-01/storage.json#L1194) both called Resource)
=> adding enum model name collision pipeline resolution

autorest/codegen/serializers/general_serializer.py, autorest/codegen/templates/config.py.jinja2
=> removed azure- prefix from ua if there

autorest/codegen/serializers/model_generic_serializer.py, autorest/codegen/serializers/model_python3_serializer.py, package.json, test/azure/Expected/AcceptanceTests/AzureParameterGrouping/azureparametergrouping/models/_models.py, test/azure/Expected/AcceptanceTests/AzureSpecials/azurespecialproperties/models/_models.py, test/azure/Expected/AcceptanceTests/Paging/paging/models/_models.py, test/azure/Expected/AcceptanceTests/StorageManagementClient/storage/models/_models.py, test/multiapi/Expected/AcceptanceTests/Multiapi/multiapi/_operations_mixin.py, test/multiapi/Expected/AcceptanceTests/Multiapi/multiapi/v2/models/_models.py, test/multiapi/Expected/AcceptanceTests/MultiapiWithSubmodule/multiapiwithsubmodule/submodule/_operations_mixin.py, test/multiapi/Expected/AcceptanceTests/MultiapiWithSubmodule/multiapiwithsubmodule/submodule/v2/models/_models.py, test/vanilla/AcceptanceTests/asynctests/test_string_tests.py, test/vanilla/AcceptanceTests/test_string_tests.py, test/vanilla/Expected/AcceptanceTests/AdditionalProperties/additionalproperties/models/_models.py, test/vanilla/Expected/AcceptanceTests/BodyComplex/bodycomplex/models/_models.py, test/vanilla/Expected/AcceptanceTests/BodyString/bodystring/aio/operations_async/_string_operations_async.py, test/vanilla/Expected/AcceptanceTests/BodyString/bodystring/operations/_string_operations.py, test/vanilla/Expected/AcceptanceTests/ExtensibleEnums/extensibleenumsswagger/models/_models.py, test/vanilla/Expected/AcceptanceTests/ModelFlattening/modelflattening/models/_models.py, test/vanilla/Expected/AcceptanceTests/ParameterFlattening/parameterflattening/models/_models.py, test/vanilla/Expected/AcceptanceTests/RequiredOptional/requiredoptional/models/_models.py, test/vanilla/Expected/AcceptanceTests/Validation/validation/models/_models.py, test/vanilla/Expected/AcceptanceTests/Xml/xmlservice/models/_models.py
fixes #531 
rebased off of #529 
example of regeneration with mgmt storage: https://github.com/Azure/azure-sdk-for-python/blob/c1e7f03946e0304af758ee49172705d2f0bd4b60/sdk/storage/azure-mgmt-storage/azure/mgmt/storage/v2019_06_01/models/_models_py3.py#L931
=> Fix default value enum py3

autorest/codegen/models/object_schema.py
fixes #527 
had to make changes to swagger, not sure if this is the route we want to go: https://github.com/Azure/azure-rest-api-specs/pull/8881
old autorest would differentiate them by calling one [ErrorResponse](https://github.com/Azure/azure-sdk-for-python/blob/c69590242bcca2a0f60521e2846b68b9ac2a9640/sdk/alertsmanagement/azure-mgmt-alertsmanagement/azure/mgmt/alertsmanagement/models/_models_py3.py#L968) and one [ErrorResponse1](https://github.com/Azure/azure-sdk-for-python/blob/c69590242bcca2a0f60521e2846b68b9ac2a9640/sdk/alertsmanagement/azure-mgmt-alertsmanagement/azure/mgmt/alertsmanagement/models/_models_py3.py#L996)
=> Fixing AlertsManagement generation (need to check if parent in yaml is of type object)

ChangeLog.md, autorest/codegen/models/parameter.py, autorest/codegen/models/parameter_list.py, test/unittests/test_parameter_ordering.py
fixes #544 
Fix: client default value only takes in whether the parameter has a specified default value. Now also checking to see if the parameter's schema has a default value.
=> fixing default value getting in operation

ChangeLog.md, autorest/codegen/models/code_model.py
Logic can now generate and is overriding parent's [name](https://github.com/Azure/azure-sdk-for-python/blob/a9c69c9154e94955005e478b8a6b79134eb2ec64/sdk/logic/azure-mgmt-logic/azure/mgmt/logic/models/_models.py#L5884). This is it in the [swagger](https://github.com/Azure/azure-rest-api-specs/blob/32bd4d8cb921e6c5cc856da82018a73de71bd0d1/specification/logic/resource-manager/Microsoft.Logic/stable/2019-05-01/logic.json#L8222)
=> Overriding parents' properties if same name

eng/pipelines/publish-release.yml
Hey folks, this change adds a new Azure DevOps pipeline to automate npm and GitHub releases for AutoRest Python v5.  This is a manual pipeline and will need to be invoked here when a release is needed:
https://dev.azure.com/azure-sdk/internal/_build?definitionId=1668&_a=summary
Let me know if you think anything needs to be added or changed.  How do you feel about the test runs here?  I didn't include everything in `ci.yml` (it's equivalent to what I did in `publish-dev-release.yml` though), is that OK?
=> Add npm release pipeline

ChangeLog.md, autorest/codegen/templates/operation_tools.jinja2, test/multiapi/Expected/AcceptanceTests/Multiapi/multiapi/v3/aio/operations_async/_operation_group_two_operations_async.py, test/multiapi/Expected/AcceptanceTests/Multiapi/multiapi/v3/operations/_operation_group_two_operations.py, test/multiapi/Expected/AcceptanceTests/MultiapiNoAsync/multiapinoasync/v3/operations/_operation_group_two_operations.py, test/multiapi/Expected/AcceptanceTests/MultiapiWithSubmodule/multiapiwithsubmodule/submodule/v3/aio/operations_async/_operation_group_two_operations_async.py, test/multiapi/Expected/AcceptanceTests/MultiapiWithSubmodule/multiapiwithsubmodule/submodule/v3/operations/_operation_group_two_operations.py, test/vanilla/Expected/AcceptanceTests/MediaTypes/mediatypes/aio/operations_async/_media_types_client_operations_async.py, test/vanilla/Expected/AcceptanceTests/MediaTypes/mediatypes/operations/_media_types_client_operations.py
fixes #610 
post_broadcast with the new docstring:
=> adding content type values to docstring

ChangeLog.md, autorest/namer/name_converter.py
fixes KeyError("protocol") issue when generating msgraph
this pr needs to be merged first so we can pass CI, since we're missing coverage rn: https://github.com/Azure/autorest.python/pull/629
=> checking for protocol in name_converter

package.json, run-python3.js
This PR adds a script that wraps logic in `@azure-tools/extension` to resolve the path to Python 3 so that a Python script file can be run from an npm script in package.json.  It uses the same Python 3 path resolution algorithm as AutoRest so that the behavior is fully consistent (and also supports AUTOREST_PYTHON_EXE).
It is invoked like so:
```
node run-python3.js script.py
```
This fixes an issue multiple users have run into where Python 3 is installed on their system with the name `python3` so we have to do some extra work to make sure we're not invoking Python 2 by accident.
=> Add run-python3.js script to fix package.json Python script runs

ChangeLog.md, autorest/codegen/models/paging_operation.py
fixes #647
search generation with fix:
=> correct item name of paging response model

package.json, test/azure/AcceptanceTests/asynctests/test_paging.py, test/azure/AcceptanceTests/test_paging.py, test/azure/Expected/AcceptanceTests/Paging/paging/aio/operations_async/_paging_operations_async.py, test/azure/Expected/AcceptanceTests/Paging/paging/models/__init__.py, test/azure/Expected/AcceptanceTests/Paging/paging/models/_models.py, test/azure/Expected/AcceptanceTests/Paging/paging/models/_models_py3.py, test/azure/Expected/AcceptanceTests/Paging/paging/operations/_paging_operations.py
testserver pr needs to be merged first: https://github.com/Azure/autorest.testserver/pull/184
=> test for paging model whose item name has an x-ms-client-name

package.json, run-python3.js
This change fixes the `run-python3.js` script so that it completes installation and successfully launches `start.py`. Re-created the PR from a local branch after my forked branch didn't work in PR #674.
=> Fix stdin passthrough when running start.py through run-python3

autorest/codegen/templates/operation.py.jinja2, autorest/codegen/templates/operation_tools.jinja2, test/azure/Expected/AcceptanceTests/AzureSpecials/azurespecialproperties/aio/operations_async/_header_operations_async.py, test/azure/Expected/AcceptanceTests/AzureSpecials/azurespecialproperties/operations/_header_operations.py, test/azure/Expected/AcceptanceTests/Head/head/aio/operations_async/_http_success_operations_async.py, test/azure/Expected/AcceptanceTests/Head/head/operations/_http_success_operations.py, test/azure/Expected/AcceptanceTests/HeadExceptions/headexceptions/aio/operations_async/_head_exception_operations_async.py, test/azure/Expected/AcceptanceTests/HeadExceptions/headexceptions/operations/_head_exception_operations.py
Typing should return bool if we are dealing with a head operation and the "head-as-bool" flag is True
=> correct return type for head operations

test/azure/requirements.txt, test/multiapi/requirements.txt, test/vanilla/requirements.txt
pytest has recently deprecated allowing the direct construction of FunctionDirect construction of Function, now has to be constructed with Function.from_parent. pytest-asyncio uses Function the old way, and they recently released an update that is compatible with the new pytest. However, we were fixing pytest-asyncio dependency to 0.10.0 (due to a previous error with 0.11.0 that got fixed, can not find what that error is though) and not getting the update. I've tried using latest pytest-asyncio and tests are passing locally
=> remove dependency on pytest-asyncio 0.10.0, getting latest version now

ChangeLog.md, autorest/codegen/models/__init__.py, autorest/codegen/models/code_model.py, autorest/codegen/models/credential_schema.py, autorest/codegen/serializers/general_serializer.py, autorest/codegen/serializers/metadata_serializer.py, test/azure/Expected/AcceptanceTests/HeadWithAzureKeyCredentialPolicy/headwithazurekeycredentialpolicy/_auto_rest_head_test_service.py, test/azure/Expected/AcceptanceTests/HeadWithAzureKeyCredentialPolicy/headwithazurekeycredentialpolicy/_configuration.py, test/azure/Expected/AcceptanceTests/HeadWithAzureKeyCredentialPolicy/headwithazurekeycredentialpolicy/aio/_auto_rest_head_test_service_async.py, test/azure/Expected/AcceptanceTests/HeadWithAzureKeyCredentialPolicy/headwithazurekeycredentialpolicy/aio/_configuration_async.py, test/multiapi/Expected/AcceptanceTests/MultiapiCredentialDefaultPolicy/multiapicredentialdefaultpolicy/_configuration.py, test/multiapi/Expected/AcceptanceTests/MultiapiCredentialDefaultPolicy/multiapicredentialdefaultpolicy/_multiapi_service_client.py, test/multiapi/Expected/AcceptanceTests/MultiapiCredentialDefaultPolicy/multiapicredentialdefaultpolicy/aio/_configuration_async.py, test/multiapi/Expected/AcceptanceTests/MultiapiCredentialDefaultPolicy/multiapicredentialdefaultpolicy/aio/_multiapi_service_client_async.py, test/multiapi/Expected/AcceptanceTests/MultiapiCredentialDefaultPolicy/multiapicredentialdefaultpolicy/v1/_configuration.py, test/multiapi/Expected/AcceptanceTests/MultiapiCredentialDefaultPolicy/multiapicredentialdefaultpolicy/v1/_metadata.json, test/multiapi/Expected/AcceptanceTests/MultiapiCredentialDefaultPolicy/multiapicredentialdefaultpolicy/v1/_multiapi_service_client.py, test/multiapi/Expected/AcceptanceTests/MultiapiCredentialDefaultPolicy/multiapicredentialdefaultpolicy/v1/aio/_configuration_async.py, test/multiapi/Expected/AcceptanceTests/MultiapiCredentialDefaultPolicy/multiapicredentialdefaultpolicy/v1/aio/_multiapi_service_client_async.py, test/multiapi/Expected/AcceptanceTests/MultiapiCredentialDefaultPolicy/multiapicredentialdefaultpolicy/v2/_configuration.py, test/multiapi/Expected/AcceptanceTests/MultiapiCredentialDefaultPolicy/multiapicredentialdefaultpolicy/v2/_metadata.json, test/multiapi/Expected/AcceptanceTests/MultiapiCredentialDefaultPolicy/multiapicredentialdefaultpolicy/v2/_multiapi_service_client.py, test/multiapi/Expected/AcceptanceTests/MultiapiCredentialDefaultPolicy/multiapicredentialdefaultpolicy/v2/aio/_configuration_async.py, test/multiapi/Expected/AcceptanceTests/MultiapiCredentialDefaultPolicy/multiapicredentialdefaultpolicy/v2/aio/_multiapi_service_client_async.py, test/multiapi/Expected/AcceptanceTests/MultiapiCredentialDefaultPolicy/multiapicredentialdefaultpolicy/v3/_configuration.py, test/multiapi/Expected/AcceptanceTests/MultiapiCredentialDefaultPolicy/multiapicredentialdefaultpolicy/v3/_metadata.json, test/multiapi/Expected/AcceptanceTests/MultiapiCredentialDefaultPolicy/multiapicredentialdefaultpolicy/v3/_multiapi_service_client.py, test/multiapi/Expected/AcceptanceTests/MultiapiCredentialDefaultPolicy/multiapicredentialdefaultpolicy/v3/aio/_configuration_async.py, test/multiapi/Expected/AcceptanceTests/MultiapiCredentialDefaultPolicy/multiapicredentialdefaultpolicy/v3/aio/_multiapi_service_client_async.py
=> Have either AzureKeyCredential typing or TokenCredential typing

autorest/codegen/__init__.py
=> fix warning for no credential scopes + default auth policy BearerTokenCredentialPolicy

ChangeLog.md, autorest/multiapi/templates/multiapi_operations_mixin.py.jinja2, autorest/multiapi/templates/multiapi_service_client.py.jinja2, test/multiapi/AcceptanceTests/asynctests/multiapi_base.py, test/multiapi/AcceptanceTests/multiapi_base.py, test/multiapi/Expected/AcceptanceTests/Multiapi/multiapi/_multiapi_service_client.py, test/multiapi/Expected/AcceptanceTests/Multiapi/multiapi/_operations_mixin.py, test/multiapi/Expected/AcceptanceTests/Multiapi/multiapi/aio/_multiapi_service_client.py, test/multiapi/Expected/AcceptanceTests/Multiapi/multiapi/aio/_operations_mixin.py, test/multiapi/Expected/AcceptanceTests/MultiapiCredentialDefaultPolicy/multiapicredentialdefaultpolicy/_multiapi_service_client.py, test/multiapi/Expected/AcceptanceTests/MultiapiCredentialDefaultPolicy/multiapicredentialdefaultpolicy/_operations_mixin.py, test/multiapi/Expected/AcceptanceTests/MultiapiCredentialDefaultPolicy/multiapicredentialdefaultpolicy/aio/_multiapi_service_client.py, test/multiapi/Expected/AcceptanceTests/MultiapiCredentialDefaultPolicy/multiapicredentialdefaultpolicy/aio/_operations_mixin.py, test/multiapi/Expected/AcceptanceTests/MultiapiCustomBaseUrl/multiapicustombaseurl/_multiapi_custom_base_url_service_client.py, test/multiapi/Expected/AcceptanceTests/MultiapiCustomBaseUrl/multiapicustombaseurl/_operations_mixin.py, test/multiapi/Expected/AcceptanceTests/MultiapiCustomBaseUrl/multiapicustombaseurl/aio/_multiapi_custom_base_url_service_client.py, test/multiapi/Expected/AcceptanceTests/MultiapiCustomBaseUrl/multiapicustombaseurl/aio/_operations_mixin.py, test/multiapi/Expected/AcceptanceTests/MultiapiDataPlane/multiapidataplane/_multiapi_service_client.py, test/multiapi/Expected/AcceptanceTests/MultiapiDataPlane/multiapidataplane/_operations_mixin.py, test/multiapi/Expected/AcceptanceTests/MultiapiDataPlane/multiapidataplane/aio/_multiapi_service_client.py, test/multiapi/Expected/AcceptanceTests/MultiapiDataPlane/multiapidataplane/aio/_operations_mixin.py, test/multiapi/Expected/AcceptanceTests/MultiapiNoAsync/multiapinoasync/_multiapi_service_client.py, test/multiapi/Expected/AcceptanceTests/MultiapiNoAsync/multiapinoasync/_operations_mixin.py, test/multiapi/Expected/AcceptanceTests/MultiapiWithSubmodule/multiapiwithsubmodule/submodule/_multiapi_service_client.py, test/multiapi/Expected/AcceptanceTests/MultiapiWithSubmodule/multiapiwithsubmodule/submodule/_operations_mixin.py, test/multiapi/Expected/AcceptanceTests/MultiapiWithSubmodule/multiapiwithsubmodule/submodule/aio/_multiapi_service_client.py, test/multiapi/Expected/AcceptanceTests/MultiapiWithSubmodule/multiapiwithsubmodule/submodule/aio/_operations_mixin.py
=> NotImplementedError -> ValueError

ChangeLog.md, autorest/codegen/templates/metadata.json.jinja2, package.json
generated network and web with this change and there's no diff
=> fix trailing comma issue

ChangeLog.md, autorest/codegen/templates/lro_operation_helper.jinja2, autorest/codegen/templates/operation.py.jinja2, autorest/codegen/templates/operation_tools.jinja2, autorest/codegen/templates/paging_operation.py.jinja2
fixes #760 
Tried it with FR's lro operations with multiple media types, and it's correctly generating docstrings there
=> add content_type docstring if multiple media types to lro and paging docs

ChangeLog.md, autorest/codegen/models/property.py, autorest/codegen/serializers/model_generic_serializer.py, autorest/codegen/serializers/model_python3_serializer.py, test/vanilla/Expected/AcceptanceTests/Constants/constants/models/_models.py, test/vanilla/Expected/AcceptanceTests/Constants/constants/models/_models_py3.py
=> set default value for properties if x-ms-client-default set

ChangeLog.md, autorest/codegen/serializers/model_generic_serializer.py, autorest/codegen/serializers/model_python3_serializer.py
fixes #811
see regen and tests in https://github.com/Azure/autorest.python/pull/816 (did not include in this PR since i didn't want to block this on testserver release)
=> set discriminator value if readonly

ChangeLog.md, autorest/codegen/models/lro_operation.py, test/azure/Expected/AcceptanceTests/Lro/lro/aio/operations/_lro_retrys_operations.py, test/azure/Expected/AcceptanceTests/Lro/lro/aio/operations/_lros_operations.py, test/azure/Expected/AcceptanceTests/Lro/lro/operations/_lro_retrys_operations.py, test/azure/Expected/AcceptanceTests/Lro/lro/operations/_lros_operations.py, test/azure/Expected/AcceptanceTests/Paging/paging/aio/operations/_paging_operations.py, test/azure/Expected/AcceptanceTests/Paging/paging/operations/_paging_operations.py, test/vanilla/Expected/AcceptanceTests/XmsErrorResponse/xmserrorresponse/aio/operations/_pet_operations.py, test/vanilla/Expected/AcceptanceTests/XmsErrorResponse/xmserrorresponse/operations/_pet_operations.py
=> fix lro response setting

autorest/codegen/__init__.py, test/multiapi/AcceptanceTests/asynctests/test_multiapi_credential_default_policy.py, test/multiapi/AcceptanceTests/test_multiapi_credential_default_policy.py, test/multiapi/Expected/AcceptanceTests/MultiapiCredentialDefaultPolicy/multiapicredentialdefaultpolicy/_configuration.py, test/multiapi/Expected/AcceptanceTests/MultiapiCredentialDefaultPolicy/multiapicredentialdefaultpolicy/aio/_configuration.py, test/multiapi/Expected/AcceptanceTests/MultiapiCredentialDefaultPolicy/multiapicredentialdefaultpolicy/v1/_configuration.py, test/multiapi/Expected/AcceptanceTests/MultiapiCredentialDefaultPolicy/multiapicredentialdefaultpolicy/v1/_metadata.json, test/multiapi/Expected/AcceptanceTests/MultiapiCredentialDefaultPolicy/multiapicredentialdefaultpolicy/v1/aio/_configuration.py, test/multiapi/Expected/AcceptanceTests/MultiapiCredentialDefaultPolicy/multiapicredentialdefaultpolicy/v2/_configuration.py, test/multiapi/Expected/AcceptanceTests/MultiapiCredentialDefaultPolicy/multiapicredentialdefaultpolicy/v2/_metadata.json, test/multiapi/Expected/AcceptanceTests/MultiapiCredentialDefaultPolicy/multiapicredentialdefaultpolicy/v2/aio/_configuration.py, test/multiapi/Expected/AcceptanceTests/MultiapiCredentialDefaultPolicy/multiapicredentialdefaultpolicy/v3/_configuration.py, test/multiapi/Expected/AcceptanceTests/MultiapiCredentialDefaultPolicy/multiapicredentialdefaultpolicy/v3/_metadata.json, test/multiapi/Expected/AcceptanceTests/MultiapiCredentialDefaultPolicy/multiapicredentialdefaultpolicy/v3/aio/_configuration.py, test/multiapi/specification/multiapicredentialdefaultpolicy/README.md
=> add default value 'api-key' for `--credential-key-header-name`

README.md, docs/generate/directives.md, docs/samples/specification/directives/readme.md, package.json, test/azure/specification/custompollerpager/README.md
So the issue seems to have appear in release [5.0.0-preview.4](https://github.com/Azure/autorest.python/releases/tag/v5.1.0-preview.4) when m4 was updated. The change in m4 was the addition of prechecker which changed the pipeline loading order and broke this hack.
Change here is to forget about loading the `python:` nested configuration before modelerfour(This shouldn't be expected anyway) but just loading it before all the other plugins so it is available.
```yaml
python: 
output-folder: ./my-python-override
python: 
modelerfour: 
some-m4-config: foo
```
To achieve #2, you should be doing:
````md
```yaml $(python)
modelerfour: 
some-m4-config: foo
```
````
Using `python:` is meant to pass configuration only for the python plugin not if `--python` has been passed
=> Fix: Loading 'python' nested config

README.md
Seems like this used to be in `master` but got removed at some point.  
Used flags defined in the documentation here https://github.com/Azure/autorest/blob/master/docs/generate/flags.md
Result when loading this extension with `--help`
=> Feature: Add help-content

ChangeLog.md, autorest/codegen/models/object_schema.py, autorest/codegen/models/parameter.py, autorest/codegen/models/property.py, autorest/codegen/serializers/model_base_serializer.py, dev_requirements.txt, package.json, test/azure/Expected/AcceptanceTests/AzureSpecials/azurespecialproperties/models/_models.py, test/azure/Expected/AcceptanceTests/AzureSpecials/azurespecialproperties/models/_models_py3.py, test/vanilla/AcceptanceTests/asynctests/test_model_flattening.py, test/vanilla/AcceptanceTests/test_model_flattening.py, test/vanilla/Expected/AcceptanceTests/BodyString/bodystring/models/_models.py, test/vanilla/Expected/AcceptanceTests/BodyString/bodystring/models/_models_py3.py, test/vanilla/Expected/AcceptanceTests/Constants/constants/models/_models.py, test/vanilla/Expected/AcceptanceTests/Constants/constants/models/_models_py3.py, test/vanilla/Expected/AcceptanceTests/ModelFlattening/modelflattening/aio/operations/_auto_rest_resource_flattening_test_service_operations.py, test/vanilla/Expected/AcceptanceTests/ModelFlattening/modelflattening/models/_models.py, test/vanilla/Expected/AcceptanceTests/ModelFlattening/modelflattening/models/_models_py3.py, test/vanilla/Expected/AcceptanceTests/ModelFlattening/modelflattening/operations/_auto_rest_resource_flattening_test_service_operations.py, test/vanilla/Expected/AcceptanceTests/Validation/validation/models/_models.py, test/vanilla/Expected/AcceptanceTests/Validation/validation/models/_models_py3.py
=> if constant is optional, don't force to value

ChangeLog.md, autorest/codegen/templates/lro_operation_helper.jinja2, package.json, test/azure/AcceptanceTests/asynctests/test_lro_parameterized_endpoints.py, test/azure/AcceptanceTests/test_lro_parameterized_endpoints.py, test/azure/Expected/AcceptanceTests/LroWithParameterizedEndpoints/lrowithparameterizedendpoints/aio/operations/_lro_with_paramaterized_endpoints_operations.py, test/azure/Expected/AcceptanceTests/LroWithParameterizedEndpoints/lrowithparameterizedendpoints/operations/_lro_with_paramaterized_endpoints_operations.py, test/vanilla/AcceptanceTests/test_zzz.py
dependent on testserver pr https://github.com/Azure/autorest.testserver/pull/293
fixes #967
=> fix lro parameterization with constant params

package.json
Don't believe this is should be required
- `autorest` is the cli
- `@autorest/autorest` I think is an outdated package from the original v3 migration
=> Remove autorest cli dependency

eng/scripts/run_pylint.py, pylintrc, test/azure/version-tolerant/tox.ini, test/llc/version-tolerant/tox.ini, test/vanilla/version-tolerant/tox.ini
there's a custom pylint plugin in azure-sdk-for-python where we've added a couple of custom linter rules. We want to include checks for these custom linter rules when linting the generated code
=> add custom pylint plugin to pylint checks

autorest/black/__init__.py
The outputFolderUri  (autorest 3.6.6) in Windows is like below:
```
\\\D:\\projects\\codegen\\autorest.python\\test\\vanilla\\legacy\\Expected\\AcceptanceTests\\Xml
```
=> fix windows: clean the outputFolderUri 

ChangeLog.md, autorest/codegen/serializers/builder_serializer.py, autorest/m4reformatter/__init__.py, docs/samples/specification/multiapi/generated/azure/multiapi/sample/v3/aio/operations/_operation_group_two_operations.py, docs/samples/specification/multiapi/generated/azure/multiapi/sample/v3/operations/_operation_group_two_operations.py, test/dpg/low-level/Expected/AcceptanceTests/DPGServiceDrivenUpdateOneLowLevel/dpgservicedrivenupdateonelowlevel/rest/params/_request_builders.py, test/dpg/low-level/Expected/AcceptanceTests/DPGServiceDrivenUpdateOneLowLevel/dpgservicedrivenupdateonelowlevel/rest/params/_request_builders_py3.py, test/dpg/version-tolerant/Expected/AcceptanceTests/DPGServiceDrivenUpdateOneVersionTolerant/dpgservicedrivenupdateoneversiontolerant/aio/operations/_operations.py, test/dpg/version-tolerant/Expected/AcceptanceTests/DPGServiceDrivenUpdateOneVersionTolerant/dpgservicedrivenupdateoneversiontolerant/operations/_operations.py, test/multiapi/Expected/AcceptanceTests/Multiapi/multiapi/v3/aio/operations/_operation_group_two_operations.py, test/multiapi/Expected/AcceptanceTests/Multiapi/multiapi/v3/operations/_operation_group_two_operations.py, test/multiapi/Expected/AcceptanceTests/MultiapiCredentialDefaultPolicy/multiapicredentialdefaultpolicy/v3/aio/operations/_operation_group_two_operations.py, test/multiapi/Expected/AcceptanceTests/MultiapiCredentialDefaultPolicy/multiapicredentialdefaultpolicy/v3/operations/_operation_group_two_operations.py, test/multiapi/Expected/AcceptanceTests/MultiapiDataPlane/multiapidataplane/v3/aio/operations/_operation_group_two_operations.py, test/multiapi/Expected/AcceptanceTests/MultiapiDataPlane/multiapidataplane/v3/operations/_operation_group_two_operations.py, test/multiapi/Expected/AcceptanceTests/MultiapiNoAsync/multiapinoasync/v3/operations/_operation_group_two_operations.py, test/multiapi/Expected/AcceptanceTests/MultiapiWithSubmodule/multiapiwithsubmodule/submodule/v3/aio/operations/_operation_group_two_operations.py, test/multiapi/Expected/AcceptanceTests/MultiapiWithSubmodule/multiapiwithsubmodule/submodule/v3/operations/_operation_group_two_operations.py, test/vanilla/legacy/Expected/AcceptanceTests/MediaTypes/mediatypes/aio/operations/_media_types_client_operations.py, test/vanilla/legacy/Expected/AcceptanceTests/MediaTypes/mediatypes/operations/_media_types_client_operations.py, test/vanilla/low-level/Expected/AcceptanceTests/MediaTypesLowLevel/mediatypeslowlevel/rest/_request_builders.py, test/vanilla/low-level/Expected/AcceptanceTests/MediaTypesLowLevel/mediatypeslowlevel/rest/_request_builders_py3.py, test/vanilla/version-tolerant/Expected/AcceptanceTests/MediaTypesVersionTolerant/mediatypesversiontolerant/_operations/_operations.py, test/vanilla/version-tolerant/Expected/AcceptanceTests/MediaTypesVersionTolerant/mediatypesversiontolerant/aio/_operations/_operations.py
fix https://github.com/Azure/autorest.python/issues/1262
=> make content_type param required with no default if streaming with no application/octet-stream

autorest/codegen/serializers/builder_serializer.py, docs/samples/specification/directives/generated/azure/directives/sample/_operations/_operations.py, docs/samples/specification/directives/generated/azure/directives/sample/aio/_operations/_operations.py, test/azure/legacy/Expected/AcceptanceTests/CustomUrlPaging/custombaseurlpaging/aio/operations/_paging_operations.py, test/azure/legacy/Expected/AcceptanceTests/CustomUrlPaging/custombaseurlpaging/operations/_paging_operations.py, test/azure/version-tolerant/Expected/AcceptanceTests/CustomPollerPagerVersionTolerant/custompollerpagerversiontolerant/aio/operations/_operations.py, test/azure/version-tolerant/Expected/AcceptanceTests/CustomPollerPagerVersionTolerant/custompollerpagerversiontolerant/operations/_operations.py, test/azure/version-tolerant/Expected/AcceptanceTests/CustomUrlPagingVersionTolerant/custombaseurlpagingversiontolerant/aio/operations/_operations.py, test/azure/version-tolerant/Expected/AcceptanceTests/CustomUrlPagingVersionTolerant/custombaseurlpagingversiontolerant/operations/_operations.py, test/azure/version-tolerant/Expected/AcceptanceTests/PagingVersionTolerant/pagingversiontolerant/aio/operations/_operations.py, test/azure/version-tolerant/Expected/AcceptanceTests/PagingVersionTolerant/pagingversiontolerant/operations/_operations.py, test/azure/version-tolerant/Expected/AcceptanceTests/StorageManagementClientVersionTolerant/storageversiontolerant/aio/operations/_operations.py, test/azure/version-tolerant/Expected/AcceptanceTests/StorageManagementClientVersionTolerant/storageversiontolerant/operations/_operations.py, test/dpg/version-tolerant/Expected/AcceptanceTests/DPGCustomizationCustomizedVersionTolerant/dpgcustomizationcustomizedversiontolerant/_operations/_operations.py, test/dpg/version-tolerant/Expected/AcceptanceTests/DPGCustomizationCustomizedVersionTolerant/dpgcustomizationcustomizedversiontolerant/aio/_operations/_operations.py, test/dpg/version-tolerant/Expected/AcceptanceTests/DPGCustomizationInitialVersionTolerant/dpgcustomizationinitialversiontolerant/_operations/_operations.py, test/dpg/version-tolerant/Expected/AcceptanceTests/DPGCustomizationInitialVersionTolerant/dpgcustomizationinitialversiontolerant/aio/_operations/_operations.py, test/dpg/version-tolerant/Expected/AcceptanceTests/DPGTestModelsVersionTolerant/dpgtestmodelsversiontolerant/_operations/_operations.py, test/dpg/version-tolerant/Expected/AcceptanceTests/DPGTestModelsVersionTolerant/dpgtestmodelsversiontolerant/aio/_operations/_operations.py
=> just do get call to next link for single operation dpg paging

ChangeLog.md, autorest/preprocess/__init__.py, package.json, test/azure/legacy/AcceptanceTests/test_zzz.py, test/azure/legacy/Expected/AcceptanceTests/CustomPollerPager/custompollerpager/aio/operations/_paging_operations.py, test/azure/legacy/Expected/AcceptanceTests/CustomPollerPager/custompollerpager/operations/_paging_operations.py, test/azure/legacy/Expected/AcceptanceTests/Paging/paging/aio/operations/_paging_operations.py, test/azure/legacy/Expected/AcceptanceTests/Paging/paging/operations/_paging_operations.py, test/azure/version-tolerant/AcceptanceTests/test_paging.py, test/azure/version-tolerant/Expected/AcceptanceTests/CustomPollerPagerVersionTolerant/custompollerpagerversiontolerant/aio/operations/_operations.py, test/azure/version-tolerant/Expected/AcceptanceTests/CustomPollerPagerVersionTolerant/custompollerpagerversiontolerant/operations/_operations.py, test/azure/version-tolerant/Expected/AcceptanceTests/PagingVersionTolerant/pagingversiontolerant/aio/operations/_operations.py, test/azure/version-tolerant/Expected/AcceptanceTests/PagingVersionTolerant/pagingversiontolerant/operations/_operations.py
=> Dont generate maxpagesize

packages/autorest.python/autorest/black/__init__.py, packages/autorest.python/autorest/cadlflags/__init__.py, packages/autorest.python/run_cadl.py
Add temporary plugin `cadlflags`. Only cadl pipeline will call it, and it will apply some of the flags from `python.json` that we expect either the cadl file, or the sidecar story to handle in the future
Right now, we're only using it to see if we want credentials for the client, and whether we want to override the namespace
=> add cadlflags plugin

packages/cadl-python/test/mock_api_tests/conftest.py
I found below issue in windows if there is no `shell=True`:
=> use shell=True to start cadl-ranch in windows 

packages/autorest.python/autorest/_utils.py, packages/autorest.python/autorest/black/__init__.py, packages/autorest.python/autorest/cadlflags/__init__.py, packages/autorest.python/autorest/codegen/__init__.py, packages/autorest.python/autorest/m2r/__init__.py, packages/autorest.python/autorest/preprocess/__init__.py, packages/autorest.python/package.json, packages/cadl-python/package.json, packages/cadl-python/src/emitter.ts
Example cadl-project.yaml
```yaml
emitters:
"@azure-tools/cadl-python":
"basic-setup-py": true
"package-version": "1.0.0b1"
```
SHould generate a basic setup.py with package version 1.0.0b1
=> allow users to pass flags through cadl-project

packages/cadl-python/src/emitter.ts
Fix https://github.com/Azure/autorest.python/issues/1473
=> Unproper model name when using template of `@azure-tools/cadl-azure-core`

packages/autorest.python/autorest/codegen/models/base.py, packages/autorest.python/autorest/codegen/models/model_type.py, packages/autorest.python/autorest/codegen/models/property.py, packages/autorest.python/autorest/codegen/serializers/model_serializer.py
In _serialization.py, the msrest deserialization just use class name directly without any namespaces.
So this PR changed generated models like below:
=> fix msrest deserialization key for private model

eng/pipelines/ci.yml, eng/pipelines/internal-ci.yml, packages/cadl-python/test/mock_api_tests/conftest.py
Right now it's broken, because we are not explicit everywhere, so the coverage step in CI is all red
=> Use default coverage report name

packages/autorest.python/autorest/codegen/models/operation_group.py, packages/autorest.python/autorest/codegen/serializers/__init__.py, packages/autorest.python/autorest/codegen/serializers/general_serializer.py, packages/autorest.python/autorest/codegen/templates/vendor.py.jinja2, packages/cadl-python/CHANGELOG.md
Fix https://github.com/Azure/autorest.python/issues/1647
=> [cadl-python] fix import and _vendor.py for subclient

packages/autorest.python/ChangeLog.md, packages/autorest.python/autorest/codegen/templates/model_base.py.jinja2, packages/cadl-python/test/generated/api-key/authentication/apikey/_model_base.py, packages/cadl-python/test/generated/dev-driven/resiliency/devdriven/_model_base.py, packages/cadl-python/test/generated/dictionary/dictionary/_model_base.py, packages/cadl-python/test/generated/extensible/enums/extensible/_model_base.py, packages/cadl-python/test/generated/fixed/enums/fixed/_model_base.py, packages/cadl-python/test/generated/hello/hello/_model_base.py, packages/cadl-python/test/generated/inheritance/models/inheritance/_model_base.py, packages/cadl-python/test/generated/item-types/arrays/itemtypes/_model_base.py, packages/cadl-python/test/generated/lro-basic/azure/lro/_model_base.py, packages/cadl-python/test/generated/oauth2/authentication/oauth2/_model_base.py, packages/cadl-python/test/generated/property-optional/models/property/optional/_model_base.py, packages/cadl-python/test/generated/property-types/models/property/types/_model_base.py, packages/cadl-python/test/generated/special-words/specialwords/_model_base.py, packages/cadl-python/test/generated/srv-driven-1/resiliency/servicedriven1/_model_base.py, packages/cadl-python/test/generated/srv-driven-2/resiliency/servicedriven2/_model_base.py, packages/cadl-python/test/generated/union/authentication/union/_model_base.py, packages/cadl-python/test/generated/usage/models/usage/_model_base.py, packages/cadl-python/test/generated/visibility/models/visibility/automatic/_model_base.py
Verified with below code:
``` python
class ByteWrapper(Model):
field: Optional[bytes] = rest_field(default=None)
mod = ByteWrapper(field=None)
assert '{}' == json.dumps(mod, cls=AzureJSONEncoder)
mod.field = azure.core.serialization.NULL
assert '{"field": null}' == json.dumps(mod, cls=AzureJSONEncoder)
```
=> serialize azure.core.serialization.NULL for DPG model

packages/cadl-python/src/emitter.ts
fix https://github.com/Azure/autorest.python/issues/1654
no header in model anymore:
https://github.com/Azure/autorest.python/blob/1fd644f44c5cbb0541ee3577f8713fa18494b762/packages/cadl-python/inference/generated_code/azure/openai/python/models/_models.py#L75-L96
=> filter header in model

packages/cadl-python/src/emitter.ts
`format: "multi"` are now generated as below:
``` python
_params["colors"] = [_SERIALIZER.query("colors", q, "str") if q is not None else "" for q in colors]
```
`format: "csv"` as below:
``` python
_params["colors"] = _SERIALIZER.query("colors", colors, "[str]", div=",")
```
=> set array format in cadl-python

packages/autorest.python/autorest/codegen/serializers/import_serializer.py, packages/autorest.python/autorest/codegen/serializers/metadata_serializer.py, packages/autorest.python/autorest/codegen/templates/metadata.json.jinja2, packages/autorest.python/autorest/multiapi/models/operation_mixin_group.py, packages/autorest.python/autorest/multiapi/serializers/__init__.py, packages/autorest.python/autorest/multiapi/serializers/import_serializer.py, packages/autorest.python/samples/specification/multiapi/generated/azure/multiapi/sample/v1/_metadata.json, packages/autorest.python/samples/specification/multiapi/generated/azure/multiapi/sample/v2/_metadata.json, packages/autorest.python/samples/specification/multiapi/generated/azure/multiapi/sample/v3/_metadata.json, packages/autorest.python/test/multiapi/Expected/AcceptanceTests/Multiapi/multiapi/v1/_metadata.json, packages/autorest.python/test/multiapi/Expected/AcceptanceTests/Multiapi/multiapi/v2/_metadata.json, packages/autorest.python/test/multiapi/Expected/AcceptanceTests/Multiapi/multiapi/v3/_metadata.json, packages/autorest.python/test/multiapi/Expected/AcceptanceTests/MultiapiCredentialDefaultPolicy/multiapicredentialdefaultpolicy/v1/_metadata.json, packages/autorest.python/test/multiapi/Expected/AcceptanceTests/MultiapiCredentialDefaultPolicy/multiapicredentialdefaultpolicy/v2/_metadata.json, packages/autorest.python/test/multiapi/Expected/AcceptanceTests/MultiapiCredentialDefaultPolicy/multiapicredentialdefaultpolicy/v3/_metadata.json, packages/autorest.python/test/multiapi/Expected/AcceptanceTests/MultiapiCustomBaseUrl/multiapicustombaseurl/v1/_metadata.json, packages/autorest.python/test/multiapi/Expected/AcceptanceTests/MultiapiCustomBaseUrl/multiapicustombaseurl/v2/_metadata.json, packages/autorest.python/test/multiapi/Expected/AcceptanceTests/MultiapiDataPlane/multiapidataplane/v1/_metadata.json, packages/autorest.python/test/multiapi/Expected/AcceptanceTests/MultiapiDataPlane/multiapidataplane/v2/_metadata.json, packages/autorest.python/test/multiapi/Expected/AcceptanceTests/MultiapiDataPlane/multiapidataplane/v3/_metadata.json, packages/autorest.python/test/multiapi/Expected/AcceptanceTests/MultiapiKeywordOnly/multiapikeywordonly/v1/_metadata.json, packages/autorest.python/test/multiapi/Expected/AcceptanceTests/MultiapiKeywordOnly/multiapikeywordonly/v2/_metadata.json, packages/autorest.python/test/multiapi/Expected/AcceptanceTests/MultiapiNoAsync/multiapinoasync/v1/_metadata.json, packages/autorest.python/test/multiapi/Expected/AcceptanceTests/MultiapiNoAsync/multiapinoasync/v2/_metadata.json, packages/autorest.python/test/multiapi/Expected/AcceptanceTests/MultiapiNoAsync/multiapinoasync/v3/_metadata.json, packages/autorest.python/test/multiapi/Expected/AcceptanceTests/MultiapiSecurity/multiapisecurity/v1/_metadata.json, packages/autorest.python/test/multiapi/Expected/AcceptanceTests/MultiapiWithSubmodule/multiapiwithsubmodule/submodule/v1/_metadata.json, packages/autorest.python/test/multiapi/Expected/AcceptanceTests/MultiapiWithSubmodule/multiapiwithsubmodule/submodule/v2/_metadata.json, packages/autorest.python/test/multiapi/Expected/AcceptanceTests/MultiapiWithSubmodule/multiapiwithsubmodule/submodule/v3/_metadata.json
supplement for https://github.com/Azure/autorest.python/pull/1774.
Test scenario: https://github.com/Azure/azure-rest-api-specs/tree/web-repro-error
`autorest D:\dev2\azure-rest-api-specs\specification\storage\resource-manager\readme.md --python --python-sdks-folder=D:\dev2\azure-sdk-for-python\sdk --version-tolerant=false  --use=@autorest\python@6.4.2 --use=@autorest\modelerfour@4.24.3 --version=3.9.2 --include-x-ms-examples-original-file --generate-sample `
=> [Mgmt][Multiapi] fix typing_definitions for `JSON`

packages/typespec-python/src/emitter.ts
Right now we raise from the emitter if we see multiple content types. Instead we want to generate abstract operations and have sdk authors handauthor them for now
cc @mpodwysocki
=> make operations abstract if multiple content types

packages/typespec-python/CHANGELOG.md, packages/typespec-python/package.json, packages/typespec-python/src/emitter.ts
getAddedOnVersion from the versioning library is getting deprecated, so switching to `getAddedOnVersions` to avoid all of the warnings
=> use getAddedOnVersions

packages/typespec-python/package.json, pnpm-lock.yaml
cadl-ranch has not released yet, but shall not affect python emitter.
=> upgrade to tsp may release

eng/pipelines/ci.yml
failure: https://dev.azure.com/azure-sdk/public/_build/results?buildId=2804363&view=logs&jobId=be972c78-f379-5e7f-c66b-c23625ee3115&j=be972c78-f379-5e7f-c66b-c23625ee3115&t=4e7b86a4-b31b-56a5-ea33-cbd6834c1e02
tox usage change after upgrade: https://github.com/Azure/azure-sdk-for-python/blob/main/CONTRIBUTING.md#whl-environment
=> fix ci failure

eng/pipelines/ci-template.yml, eng/pipelines/nightly.yml
Any tsp core lib change may cause minor code diff for emitter, but we do not care about that in nightly build, we just care about the compile and test pass. So, this PR introduce a new flag for `ci-template.yml` and diasble diff check for nightly build.
=> do not do diff check when nightly build

packages/typespec-python/src/lib.ts
["package-dir"](https://github.com/openapi-env-test/azure-rest-api-specs/pull/3657/files#diff-b7e75220b6f450282cba2075cfb681c5c83cbb0090b9e5d3784ba768c55a09b5) is used in automation of pipeline but cause compiler error in python emitter. So we update emitter config to avoid it.
=> compatible with automation config

packages/autorest.python/autorest/codegen/models/paging_operation.py, packages/typespec-python/CHANGELOG.md
https://github.com/Azure/autorest.python/issues/2055
=> Fix generation error when `next_link` in undefined

packages/autorest.python/tasks.py
When running `inv regenerate`, there is some difference between my local PC and pipeline:
I find it is related with autorest version. To make sure the running result is same, we shall ensure to same version of autorest and m4 in different environments.
=> set autrest and m4 version for test

packages/autorest.python/autorest/codegen/models/property.py
fixes https://github.com/Azure/autorest.python/issues/2191
=> fix json template when description contains `\n`

packages/typespec-python/src/emitter.ts
fixes https://github.com/Azure/autorest.python/issues/2345
=> fix parse error for `package-pprint-name` in `tspconfig.yaml`

eng/pipelines/internal-ci.yml, package.json, packages/typespec-python/package.json, pnpm-lock.yaml
- bump cadl-ranch
- update ci to upload coverage report for unbranded/azure with reference of https://github.com/Azure/autorest.csharp/pull/4144
=> Bump cadl ranch 0.28.7

packages/autorest.python/ChangeLog.md, packages/autorest.python/autorest/postprocess/__init__.py, packages/autorest.python/autorest/postprocess/venvtools.py, packages/autorest.python/install.py, packages/autorest.python/package.json, packages/autorest.python/start.py, packages/autorest.python/venvtools.py, packages/typespec-python/CHANGELOG.md, packages/typespec-python/package.json
Should solve:
https://stackoverflow.com/questions/77238856/problems-installing-libraries-via-pip-after-installing-python-3-12
https://stackoverflow.com/questions/77364550/attributeerror-module-pkgutil-has-no-attribute-impimporter-did-you-mean
For instance:
=> Upgrade pip when creating venv

packages/autorest.python/autorest/black/__init__.py, packages/typespec-python/README.md
fixes https://github.com/Azure/autorest.python/issues/2497
The PR includes 2 parts:
- skip `.tox`/`.mypy_cache` for black
- try/catch file.read so that trackback could show which file fails.
=> optimize black

packages/autorest.python/CHANGELOG.md, packages/autorest.python/autorest/codegen/serializers/builder_serializer.py, packages/autorest.python/package.json, packages/typespec-python/CHANGELOG.md, packages/typespec-python/package.json
Currently, we just do `JSON_REGEXP.match` on the full default content type string itself. The `JSON_REGEXP` (which we've copied from core), ensures that the content type ends with the string `"json"`. However, in content types with charsets, i.e. `"application/cloud-events+json; charset=utf-8"`, we fail this check because we don't split on `";"` first.
This PR checks that a input model is expected to be json serializable by first splitting the content type on the `";"` string, then checking it against the `JSON_REGEXP`.
This was causing a bug in event grid serialization, since we weren't json encoding one of their models before sending it to the service
cc @l0lawrence
=> check json regexp on first half of content type

packages/autorest.python/autorest/codegen/serializers/client_serializer.py, packages/autorest.python/autorest/codegen/serializers/model_serializer.py, packages/autorest.python/autorest/codegen/templates/enum.py.jinja2, packages/autorest.python/autorest/codegen/templates/enum_container.py.jinja2, packages/autorest.python/autorest/codegen/templates/model_container.py.jinja2, packages/autorest.python/autorest/codegen/templates/model_dpg.py.jinja2, packages/autorest.python/autorest/codegen/templates/model_msrest.py.jinja2, packages/autorest.python/autorest/codegen/templates/operation_tools.jinja2
If we escape backslashes in docstring, we won't face "invalid escape" warnings.
Fixes #2551
=> Escape backslashes in docstring

.chronus/changes/fix_body_root-2024-4-31-12-40-38.md, packages/autorest.python/autorest/preprocess/__init__.py, packages/typespec-python/test/azure/generated/payload-multipart/payload/multipart/aio/operations/_operations.py, packages/typespec-python/test/azure/generated/payload-multipart/payload/multipart/operations/_operations.py, packages/typespec-python/test/unbranded/generated/payload-multipart/payload/multipart/aio/operations/_operations.py, packages/typespec-python/test/unbranded/generated/payload-multipart/payload/multipart/operations/_operations.py
=> don't lowercase serialized body entries

.chronus/changes/add-usage-2024-5-11-16-39-4.md, packages/autorest.python/autorest/codegen/models/model_type.py, packages/autorest.python/autorest/codegen/templates/model_dpg.py.jinja2, packages/typespec-python/src/types.ts, packages/typespec-python/test/azure/generated/authentication-api-key/authentication/apikey/models/_models.py, packages/typespec-python/test/azure/generated/authentication-http-custom/authentication/http/custom/models/_models.py, packages/typespec-python/test/azure/generated/authentication-oauth2/authentication/oauth2/models/_models.py, packages/typespec-python/test/azure/generated/azure-client-generator-core-access/specs/azure/clientgenerator/core/access/models/_models.py, packages/typespec-python/test/azure/generated/azure-core-basic/specs/azure/core/basic/models/_models.py, packages/typespec-python/test/azure/generated/azure-core-lro-standard/specs/azure/core/lro/standard/models/_models.py, packages/typespec-python/test/azure/generated/azure-core-traits/specs/azure/core/traits/models/_models.py, packages/typespec-python/test/azure/generated/azure-mgmt-spheredpg/azure/mgmt/spheredpg/models/_models.py, packages/typespec-python/test/azure/generated/azurecore-lro-rpc/azurecore/lro/rpc/models/_models.py, packages/typespec-python/test/azure/generated/payload-content-negotiation/payload/contentnegotiation/models/_models.py, packages/typespec-python/test/azure/generated/payload-pageable/payload/pageable/models/_models.py, packages/typespec-python/test/azure/generated/typetest-model-singlediscriminator/typetest/model/singlediscriminator/models/_models.py, packages/typespec-python/test/azure/generated/typetest-model-usage/typetest/model/usage/models/_models.py, packages/typespec-python/test/azure/generated/typetest-union/typetest/union/models/_models.py, packages/typespec-python/test/unbranded/generated/authentication-api-key/authentication/apikey/models/_models.py, packages/typespec-python/test/unbranded/generated/authentication-http-custom/authentication/http/custom/models/_models.py, packages/typespec-python/test/unbranded/generated/authentication-oauth2/authentication/oauth2/models/_models.py, packages/typespec-python/test/unbranded/generated/payload-content-negotiation/payload/contentnegotiation/models/_models.py, packages/typespec-python/test/unbranded/generated/payload-pageable/payload/pageable/models/_models.py, packages/typespec-python/test/unbranded/generated/typetest-model-singlediscriminator/typetest/model/singlediscriminator/models/_models.py, packages/typespec-python/test/unbranded/generated/typetest-model-usage/typetest/model/usage/models/_models.py, packages/typespec-python/test/unbranded/generated/typetest-union/typetest/union/models/_models.py
fixes https://github.com/Azure/autorest.python/issues/2623
=> Remove unnecessary doc for model which is only used for output

eng/pipelines/ci-template.yml
fixes https://github.com/Azure/autorest.python/issues/2669
=> fix nightly pipeline

.chronus/changes/HEAD-2024-6-4-17-48-51.md, .chronus/changes/fix-bug-header-2024-6-5-13-41-56.md, packages/autorest.python/test/vanilla/legacy/Expected/AcceptanceTests/BodyString/bodystring/operations/_enum_operations.py, packages/typespec-python/generator/pygen/codegen/serializers/builder_serializer.py, packages/typespec-python/generator/pygen/codegen/serializers/parameter_serializer.py, packages/typespec-python/generator/pygen/codegen/templates/request_builder.py.jinja2
fixes https://github.com/Azure/autorest.python/issues/2670
=> Fix for construct headers and queries when build request

eng/pipelines/nightly.yml
https://dev.azure.com/azure-sdk/public/_build/results?buildId=3959124&view=results, default timeout is 60 minutes:
However, all pipelines have a default step named `Finalize CodeQL (auto-injected)` which costs much time and sometimes cause nightly build timeout.
=> Update nightly.yml for timeout limit

.chronus/changes/exclue-venv-2024-6-22-15-39-49.md, packages/typespec-python/generator/pygen/__init__.py, packages/typespec-python/generator/pygen/black.py
fix https://github.com/Azure/autorest.python/issues/2705
regenerate sdk: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3981401&view=results
SDK regenerate PR: https://github.com/Azure/azure-sdk-for-python/pull/36561
=> Skip to format files under `venv` and `env`

eng/pipelines/publish-release.yml, packages/autorest.python/requirements.txt
https://github.com/Azure/autorest.python/pull/2718 doesn't fix the error of release pipeline.
Using python3.10 instead of 3.8 could avoid this error: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3993212&view=logs&j=19992227-62fb-5b50-4e29-3b72bd33eea1&t=9281c869-17dc-5ef7-6bc6-1c1da071debd
=> fix release pipeline to unblock package release

.chronus/changes/fix-discriminator-initialize-2024-7-1-11-29-41.md, packages/typespec-python/generator/pygen/codegen/templates/model_dpg.py.jinja2
fix https://github.com/Azure/autorest.python/issues/2735
=> Fix discriminator initialize

.chronus/changes/HEAD-2024-7-9-10-25-50.md, packages/typespec-python/generator/pygen/codegen/models/parameter.py, packages/typespec-python/scripts/regenerate.ts, packages/typespec-python/src/types.ts, packages/typespec-python/test/azure/generated/azure-resource-manager-models-common-types-managed-identity/azure/resourcemanager/models/commontypes/managedidentity/_client.py, packages/typespec-python/test/azure/generated/azure-resource-manager-models-common-types-managed-identity/azure/resourcemanager/models/commontypes/managedidentity/_configuration.py, packages/typespec-python/test/azure/generated/azure-resource-manager-models-common-types-managed-identity/azure/resourcemanager/models/commontypes/managedidentity/aio/_client.py, packages/typespec-python/test/azure/generated/azure-resource-manager-models-common-types-managed-identity/azure/resourcemanager/models/commontypes/managedidentity/aio/_configuration.py, packages/typespec-python/test/azure/generated/azure-resource-manager-models-common-types-managed-identity/azure/resourcemanager/models/commontypes/managedidentity/aio/operations/_operations.py, packages/typespec-python/test/azure/generated/azure-resource-manager-models-common-types-managed-identity/azure/resourcemanager/models/commontypes/managedidentity/operations/_operations.py, packages/typespec-python/test/azure/generated/azure-resource-manager-models-resources/azure/resourcemanager/models/resources/_client.py, packages/typespec-python/test/azure/generated/azure-resource-manager-models-resources/azure/resourcemanager/models/resources/_configuration.py, packages/typespec-python/test/azure/generated/azure-resource-manager-models-resources/azure/resourcemanager/models/resources/aio/_client.py, packages/typespec-python/test/azure/generated/azure-resource-manager-models-resources/azure/resourcemanager/models/resources/aio/_configuration.py, packages/typespec-python/test/azure/generated/azure-resource-manager-models-resources/azure/resourcemanager/models/resources/aio/operations/_operations.py, packages/typespec-python/test/azure/generated/azure-resource-manager-models-resources/azure/resourcemanager/models/resources/operations/_operations.py, packages/typespec-python/test/azure/mock_api_tests/asynctests/test_azure_arm_models_resource_async.py, packages/typespec-python/test/azure/mock_api_tests/conftest.py, packages/typespec-python/test/azure/mock_api_tests/test_azure_arm_models_resource.py
Revert client signature `endpoint` to `base_url` to avoid breaking for Mgmt SDK
=> Revert client signature `endpoint` to `base_url` to avoid breaking for Mgmt SDK

eng/scripts/sdk_regenerate.py
Add step to update commit id in `tsp-location.yaml` to avoid failure caused by outdated typespec
=> fix sdk regeneration pipeline

.chronus/changes/fix-pylint-2024-09-12-2024-8-12-16-9-4.md, packages/typespec-python/generator/pygen/codegen/serializers/model_serializer.py
fix https://github.com/Azure/autorest.python/issues/2833
=> Fix "line-too-long" for property of model

.chronus/changes/bump_dependencies-2024-8-19-16-21-8.md, .chronus/changes/bump_tcgc-2024-8-23-11-25-33.md, .chronus/changes/fix-multipart-2024-2024-8-23-16-11-40.md, packages/autorest.python/CHANGELOG.md, packages/autorest.python/package.json, packages/typespec-python/CHANGELOG.md, packages/typespec-python/package.json
After bump tcgc@0.46.1, we need to release a new version of typespec-python to unblock ARM SDK release.
=> release for typespec-python 0.33.0

.chronus/changes/bump_version-2024-9-11-16-56-37.md, .chronus/changes/bump_version-2024-9-12-11-41-53.md, packages/autorest.python/CHANGELOG.md, packages/autorest.python/package.json, packages/typespec-python/CHANGELOG.md, packages/typespec-python/package.json
release for typespec-python 0.36.0 && autorest.python 6.26.0
=> release for typespec-python 0.36.0 && autorest.python 6.26.0

.chronus/changes/update-package-2024-9-24-8-33-7.md, packages/autorest.python/package.json, pnpm-lock.yaml
Move `@typespec/http-client-python` from "devDependencies" to "dependencies"
=> Move `@typespec/http-client-python` from "devDependencies" to "dependencies"

.chronus/changes/update-package-2024-2024-9-31-9-52-24.md, package.json, packages/typespec-python/package.json, pnpm-lock.yaml
Since only typespec-python use cadl-ranch, we shall move all related dependencies into this folder which is more convenient to manage.
=> move devDependency `@azure-tools/cadl-ranch` to typespec-python folder

.chronus/changes/multiapi_mypy-2025-0-6-15-4-4.md, packages/autorest.python/autorest/multiapi/templates/multiapi_service_client.py.jinja2, packages/autorest.python/samples/specification/multiapi/generated/azure/multiapi/sample/_multiapi_service_client.py, packages/autorest.python/samples/specification/multiapi/generated/azure/multiapi/sample/aio/_multiapi_service_client.py, packages/autorest.python/test/multiapi/Expected/AcceptanceTests/Multiapi/multiapi/_multiapi_service_client.py, packages/autorest.python/test/multiapi/Expected/AcceptanceTests/Multiapi/multiapi/aio/_multiapi_service_client.py, packages/autorest.python/test/multiapi/Expected/AcceptanceTests/MultiapiCredentialDefaultPolicy/multiapicredentialdefaultpolicy/_multiapi_service_client.py, packages/autorest.python/test/multiapi/Expected/AcceptanceTests/MultiapiCredentialDefaultPolicy/multiapicredentialdefaultpolicy/aio/_multiapi_service_client.py, packages/autorest.python/test/multiapi/Expected/AcceptanceTests/MultiapiCustomBaseUrl/multiapicustombaseurl/_multiapi_custom_base_url_service_client.py, packages/autorest.python/test/multiapi/Expected/AcceptanceTests/MultiapiCustomBaseUrl/multiapicustombaseurl/aio/_multiapi_custom_base_url_service_client.py, packages/autorest.python/test/multiapi/Expected/AcceptanceTests/MultiapiDataPlane/multiapidataplane/_multiapi_service_client.py, packages/autorest.python/test/multiapi/Expected/AcceptanceTests/MultiapiDataPlane/multiapidataplane/aio/_multiapi_service_client.py, packages/autorest.python/test/multiapi/Expected/AcceptanceTests/MultiapiKeywordOnly/multiapikeywordonly/_multiapi_service_client.py, packages/autorest.python/test/multiapi/Expected/AcceptanceTests/MultiapiKeywordOnly/multiapikeywordonly/aio/_multiapi_service_client.py, packages/autorest.python/test/multiapi/Expected/AcceptanceTests/MultiapiNoAsync/multiapinoasync/_multiapi_service_client.py, packages/autorest.python/test/multiapi/Expected/AcceptanceTests/MultiapiSecurity/multiapisecurity/_multiapi_service_client.py, packages/autorest.python/test/multiapi/Expected/AcceptanceTests/MultiapiSecurity/multiapisecurity/aio/_multiapi_service_client.py, packages/autorest.python/test/multiapi/Expected/AcceptanceTests/MultiapiWithSubmodule/multiapiwithsubmodule/submodule/_multiapi_service_client.py, packages/autorest.python/test/multiapi/Expected/AcceptanceTests/MultiapiWithSubmodule/multiapiwithsubmodule/submodule/aio/_multiapi_service_client.py, packages/autorest.python/test/multiapi/Expected/AcceptanceTests/multiapicombiner/multiapicombiner/_client.py, packages/autorest.python/test/multiapi/Expected/AcceptanceTests/multiapicombiner/multiapicombiner/aio/_client.py
=> update mypy for pipeline client in multiapi base

.chronus/changes/HEAD-2025-0-23-15-44-58.md, .chronus/changes/HEAD-2025-0-23-15-45-7.md, packages/autorest.python/CHANGELOG.md, packages/autorest.python/package.json, packages/typespec-python/CHANGELOG.md, packages/typespec-python/package.json, packages/typespec-python/scripts/eng/regenerate.ts, packages/typespec-python/test/azure/generated/authentication-http-custom/README.md, packages/typespec-python/test/azure/generated/authentication-http-custom/setup.py, packages/typespec-python/test/unbranded/generated/authentication-http-custom/setup.py, pnpm-lock.yaml
fix https://github.com/Azure/azure-sdk-tools/issues/9749
=> release a new version

.chronus/changes/fix-nightly-2025-2-3-17-27-31.md, eng/pipelines/ci-template.yml, packages/typespec-python/scripts/eng/regenerate.ts
fix https://github.com/microsoft/typespec/issues/6211
=> fix nightly build

docs/developer/sdk_from_swagger_and_typespec.md
fix https://github.com/microsoft/typespec/issues/7315
=> Detailed doc about difference between MGmt SDK generated from swagger and typespec which is converted from swagger

packages/typespec-python/test/azure/mock_api_tests/asynctests/test_azure_arm_operationtemplates_async.py, packages/typespec-python/test/azure/mock_api_tests/test_azure_arm_operationtemplates.py
sync pr: https://github.com/microsoft/typespec/pull/8210/files
=> add testcases
